# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 09:58
from __future__ import unicode_literals

import amuse.db.models
import bitfield.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import releases.models
import storages.backends.s3boto3


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codes', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                (
                    'role',
                    models.SmallIntegerField(choices=[(1, 'Featured'), (2, 'Writer')]),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CoverArt',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    amuse.db.models.ImageWithThumbsField(
                        storage=storages.backends.s3boto3.S3Boto3Storage(
                            bucket_name='amuse-cover-art-uploaded-brodd',
                            querystring_auth=False,
                        ),
                        upload_to=releases.models.uploaded_directory_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[(1, 'Approved'), (2, 'Pending')], default=2
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Genre',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.SmallIntegerField(choices=[(1, 'Album'), (2, 'Single')]),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'label',
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    'flags',
                    bitfield.models.BitField(
                        (
                            (
                                'DISTRIBUTED_BEFORE',
                                'Content has been distributed before',
                            ),
                        ),
                        default=None,
                    ),
                ),
                ('release_date', models.DateField()),
                (
                    'completed',
                    models.BooleanField(
                        default=False,
                        help_text='The release creation is complete. <strong>Must not</strong> be set manually.',
                    ),
                ),
                (
                    'approved',
                    models.BooleanField(
                        default=False,
                        help_text='The release is approved and ready for delivery. <strong>Must</strong> be set manually.',
                    ),
                ),
                (
                    'delivery_status',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'Pending'),
                            (1, 'Started'),
                            (2, 'Success'),
                            (3, 'Failed'),
                        ],
                        default=0,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'countries',
                    models.ManyToManyField(
                        help_text='This is the countries to <strong>include</strong> in delivery.',
                        to='countries.Country',
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Genre',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('sequence', models.SmallIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'version',
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ('recording_year', models.SmallIntegerField()),
                (
                    'recording_place_id',
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                ('explicit', models.BooleanField(default=False)),
                ('rights', models.BooleanField(default=True)),
                (
                    'genre',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='songs',
                        to='releases.Genre',
                    ),
                ),
                (
                    'isrc',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='codes.ISRC'
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='songs',
                        to='releases.Release',
                    ),
                ),
            ],
            options={'ordering': ['sequence']},
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.SmallIntegerField(choices=[(1, 'FLAC'), (2, 'MP3')])),
                ('duration', models.PositiveSmallIntegerField()),
                (
                    'file',
                    models.FileField(
                        storage=storages.backends.s3boto3.S3Boto3Storage(
                            bucket_name='amuse-song-file-transcoded-brodd'
                        ),
                        upload_to='',
                    ),
                ),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='releases.Song',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SongFileUpload',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'transcode_id',
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ('link', models.TextField(default=None, null=True)),
                (
                    'file',
                    models.FileField(
                        null=True,
                        storage=storages.backends.s3boto3.S3Boto3Storage(
                            bucket_name='amuse-song-file-uploaded-brodd'
                        ),
                        upload_to=releases.models.uploaded_directory_path,
                    ),
                ),
                (
                    'song',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Song',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='stores',
            field=models.ManyToManyField(
                blank=True,
                help_text='This is the stores to <strong>exclude</strong> from delivery.',
                to='releases.Store',
            ),
        ),
        migrations.AddField(
            model_name='release',
            name='upc',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='codes.UPC'
            ),
        ),
        migrations.AddField(
            model_name='release',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='releases',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='coverart',
            name='release',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cover_art',
                to='releases.Release',
            ),
        ),
        migrations.AddField(
            model_name='coverart',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='contributor',
            name='song',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contributors',
                to='releases.Song',
            ),
        ),
    ]
