# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-18 08:54
from __future__ import unicode_literals

import amuse.db.models
from django.conf import settings
from django.db import migrations, models
import releases.models
import storages.backends.s3boto3


class Migration(migrations.Migration):
    dependencies = [('releases', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='coverart',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='coverart',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='coverart',
            name='file',
            field=amuse.db.models.ImageWithThumbsField(
                height_field='height',
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket_name=settings.AWS_COVER_ART_UPLOADED_BUCKET_NAME,
                    querystring_auth=False,
                ),
                upload_to=releases.models.uploaded_directory_path,
                width_field='width',
            ),
        ),
        migrations.AlterField(
            model_name='songfileupload',
            name='file',
            field=models.FileField(
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket_name=settings.AWS_COVER_ART_UPLOADED_BUCKET_NAME
                ),
                upload_to='',
            ),
        ),
    ]
