# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-18 09:12
from __future__ import unicode_literals

from django.db import migrations


def populate_coverart_sizes(apps, schema_editor):
    CoverArt = apps.get_model('releases', 'CoverArt')
    for coverart in CoverArt.objects.all():
        if coverart.file is not None and coverart.file.name:
            coverart.width = coverart.file.width
            coverart.height = coverart.file.height
            coverart.save()


class Migration(migrations.Migration):
    dependencies = [('releases', '0002_auto_20160618_0854')]

    operations = [migrations.RunPython(populate_coverart_sizes)]
