# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-18 10:02
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):
    dependencies = [('releases', '0003_auto_20160618_0912')]

    operations = [
        migrations.AlterField(
            model_name='songfileupload',
            name='file',
            field=models.FileField(
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket_name=settings.AWS_SONG_FILE_UPLOADED_BUCKET_NAME
                ),
                upload_to='',
            ),
        )
    ]
