# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0005_unique_genre_name')]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.SmallIntegerField(
                choices=[(1, 'Featured'), (2, 'Writer'), (3, 'Producer')]
            ),
        )
    ]
