# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-08 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('codes', '0002_unique_code_field'),
        ('releases', '0006_auto_20160721_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDailyDownloadStats',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                (
                    'isrc',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='codes.ISRC'
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='SongDailyStreamStats',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                (
                    'isrc',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='codes.ISRC'
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AlterUniqueTogether(
            name='songdailystreamstats', unique_together=set([('isrc', 'date')])
        ),
        migrations.AlterUniqueTogether(
            name='songdailydownloadstats', unique_together=set([('isrc', 'date')])
        ),
    ]
