# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0008_release_comments')]

    operations = [
        migrations.AlterModelOptions(
            name='comments', options={'verbose_name_plural': 'Comments'}
        ),
        migrations.AlterModelOptions(name='genre', options={'ordering': ('name',)}),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(
                help_text='Internal comments about current release.'
            ),
        ),
    ]
