# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0009_auto_20160905_1127')]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.URLField(blank=True, max_length=255, null=True),
        )
    ]
