# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0010_stores_logo_blank')]

    operations = [
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('platform', models.SmallIntegerField(choices=[(1, 'Android')])),
                ('version', models.CharField(max_length=32)),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Release',
                    ),
                ),
            ],
        )
    ]
