# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-15 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0011_platforminfo')]

    operations = [
        migrations.AddField(
            model_name='store',
            name='org_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        )
    ]
