# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0012_store_org_id')]

    operations = [
        migrations.AddField(
            model_name='release',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
