# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0019_genre_subgenres_field')]

    operations = [
        migrations.AddField(
            model_name='store',
            name='order',
            field=models.PositiveSmallIntegerField(default=999),
        )
    ]
