# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [('releases', '0021_delete_legacy_stats')]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='file',
            field=models.FileField(
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    bucket_name=settings.AWS_SONG_FILE_TRANSCODED_BUCKET_NAME
                ),
                upload_to='',
            ),
        )
    ]
