# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-08 08:35
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0023_auto_20170529_1239')]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='rejection_flags',
            field=bitfield.models.BitField(
                (
                    ('artwork_social-media', 'Artwork: Social media logos'),
                    ('artwork_text', 'Artwork: Text'),
                    ('artwork_format', 'Artwork: Format'),
                    ('artwork_size', 'Artwork: Size'),
                    ('artwork_blurry', 'Artwork: Blurry'),
                    ('explicit_parental-advisory', 'Explicit: Parental advisory logo'),
                    ('titles_differs', 'Titles differs'),
                    ('release_date-changed', 'Release date changed'),
                ),
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='song',
            name='rejection_flags',
            field=bitfield.models.BitField(
                (
                    ('rights_samplings', 'Contains samplings'),
                    ('rights_remix', 'Remix'),
                    ('rights_no-rights', 'No rights'),
                    ('audio_bad-quality', 'Audio: Bad quality'),
                    ('audio_missing-file', 'Audio: Missing file'),
                    ('explicit_lyrics', 'Explicit: Lyrics'),
                    ('genre_not-approved', 'Not approved genre'),
                ),
                default=None,
                null=True,
            ),
        ),
    ]
