# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-08 10:31
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0024_auto_20170608_0835')]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='rejection_flags',
            field=bitfield.models.BitField(
                (
                    ('rights_samplings', 'Contains samplings'),
                    ('rights_remix', 'Remix'),
                    ('rights_no-rights', 'No rights'),
                    ('audio_bad-quality', 'Audio: Bad quality'),
                    ('explicit_lyrics', 'Explicit: Lyrics'),
                    ('genre_not-approved', 'Not approved genre'),
                ),
                default=None,
                null=True,
            ),
        )
    ]
