# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0029_auto_20170705_2312')]

    operations = [
        migrations.CreateModel(
            name='MetadataLanguage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=120)),
                (
                    'fuga_code',
                    models.CharField(
                        blank=True, default='en', max_length=25, null=True, unique=True
                    ),
                ),
            ],
            options={'ordering': ('name',)},
        )
    ]
