# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-04 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0029_auto_20170705_2312')]

    operations = [
        migrations.CreateModel(
            name='AudibleMagicMatch',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.CharField(max_length=128)),
                ('track', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=128)),
                ('upc', models.CharField(max_length=128)),
                ('isrc', models.CharField(max_length=128)),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='releases.Song'
                    ),
                ),
            ],
        )
    ]
