# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-19 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0031_release_meta_language')]

    operations = [
        migrations.AddField(
            model_name='song',
            name='meta_language',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='releases.MetadataLanguage',
            ),
        )
    ]
