# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-30 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0032_song_meta_language')]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='meta_language',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='releases.MetadataLanguage',
            ),
        ),
        migrations.AlterField(
            model_name='song',
            name='meta_language',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='releases.MetadataLanguage',
            ),
        ),
    ]
