# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-04 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0033_auto_20170830_0932'),
        ('releases', '0030_audiblemagicmatch'),
    ]

    operations = []
