# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-14 18:10
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


def migrate_fwd(apps, schema_editor):
    Song = apps.get_model('releases.Song')
    for song in Song.objects.filter(explicit=True):
        song.meta_flags.explicit |= Song.meta_flags.explicit
        song.save()


def migrate_bwd(apps, schema_editor):
    Song = apps.get_model('releases.Song')
    for song in Song.objects.filter(meta_flags=Song.meta_flags.explicit):
        song.explicit = True
        song.save()


class Migration(migrations.Migration):
    dependencies = [('releases', '0034_merge')]

    operations = [
        migrations.AddField(
            model_name='song',
            name='meta_flags',
            field=bitfield.models.BitField(
                (
                    ('beats', 'Track contains beats.'),
                    ('cover', 'Track is a cover.'),
                    ('explicit', 'Track has explicit lyrics.'),
                    ('remix', 'Track is a remix.'),
                    ('samples', 'Track contains samples.'),
                ),
                default=None,
                null=True,
            ),
        ),
        migrations.RunPython(migrate_fwd, migrate_bwd),
    ]
