# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-14 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0035_song_meta_flags')]

    operations = [
        migrations.RemoveField(model_name='song', name='explicit'),
        migrations.RemoveField(model_name='song', name='rights'),
    ]
