# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0036_auto_20170914_1817')]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
