# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-21 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0037_release_release_version'),
        ('releases', '0037_release_status_deleted'),
    ]

    operations = []
