# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0038_merge')]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='apple_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        )
    ]
