# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-02-01 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0039_genre_apple_code')]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='apple_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        )
    ]
