# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-19 12:28
from __future__ import unicode_literals

import amuse.db.models
import amuse.storages
from django.conf import settings
from django.db import migrations, models
import releases.models


class Migration(migrations.Migration):
    dependencies = [('releases', '0041_added_ep_type')]

    operations = [
        migrations.AlterField(
            model_name='coverart',
            name='file',
            field=amuse.db.models.ImageWithThumbsField(
                height_field='height',
                storage=amuse.storages.S3Storage(
                    bucket_name=settings.AWS_COVER_ART_UPLOADED_BUCKET_NAME,
                    querystring_auth=False,
                ),
                upload_to=releases.models.uploaded_directory_path,
                width_field='width',
            ),
        ),
        migrations.AlterField(
            model_name='songfile',
            name='file',
            field=models.FileField(
                storage=amuse.storages.S3Storage(
                    bucket_name=settings.AWS_SONG_FILE_TRANSCODED_BUCKET_NAME
                ),
                upload_to='',
            ),
        ),
    ]
