# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0040_contributor_apple_id')]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.SmallIntegerField(
                choices=[(1, 'Album'), (2, 'Single'), (3, 'EP')]
            ),
        )
    ]
