# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0041_auto_20180419_1228')]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'Featured'),
                    (2, 'Writer'),
                    (3, 'Producer'),
                    (4, 'Primary'),
                    (5, 'Mixer'),
                    (6, 'Remixer'),
                ]
            ),
        )
    ]
