# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0043_removed_primary_role_contributor')]

    operations = [
        migrations.AddField(
            model_name='song',
            name='meta_audio_locale',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audio_locale',
                to='releases.MetadataLanguage',
            ),
        )
    ]
