# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-28 09:13
from __future__ import unicode_literals

from django.db import migrations, models


def migrate(apps, schema_editor):
    Song = apps.get_model('releases', 'Song')
    for song in Song.objects.filter(meta_flags=Song.meta_flags.explicit):
        song.explicit = 1
        song.save()

    for song in Song.objects.filter(meta_flags=Song.meta_flags.remix):
        song.origin = 3
        song.save()

    for song in Song.objects.filter(meta_flags=Song.meta_flags.cover):
        song.origin = 2
        song.save()


def rollback(apps, schema_editor):
    Song = apps.get_model('releases', 'Song')
    for song in Song.objects.filter(explicit=1):
        song.meta_flags.explicit = True
        song.save()

    for song in Song.objects.filter(origin=2):
        song.meta_flags.cover = True
        song.save()

    for song in Song.objects.filter(origin=3):
        song.meta_flags.remix = True
        song.save()


class Migration(migrations.Migration):
    dependencies = [('releases', '0044_song_meta_audio_locale')]

    operations = [
        migrations.AddField(
            model_name='song',
            name='explicit',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'none'), (1, 'explicit'), (2, 'clean')], default=0
            ),
        ),
        migrations.AddField(
            model_name='song',
            name='origin',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'original'), (2, 'cover'), (3, 'remix')], default=1
            ),
        ),
        migrations.RunPython(migrate, rollback),
    ]
