# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0046_remove_meta_flags')]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'featured_artist'),
                    (2, 'writer'),
                    (3, 'producer'),
                    (4, 'mixer'),
                    (5, 'remixer'),
                ]
            ),
        )
    ]
