# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-28 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0048_excluded_countries_stores')]

    operations = [migrations.RemoveField(model_name='release', name='countries')]
