# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0051_fix_song_properties')]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.SmallIntegerField(
                choices=[(1, 'album'), (2, 'single'), (3, 'ep')]
            ),
        )
    ]
