# Generated by Django 2.0.5 on 2018-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0052_release_type_labels')]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='status',
            field=models.SmallIntegerField(
                choices=[(1, 'active'), (2, 'inactive')], default=1
            ),
        )
    ]
