# Generated by Django 2.0.6 on 2018-07-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0054_release_history')]

    operations = [
        migrations.AddField(
            model_name='historicalrelease',
            name='original_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='original_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
