# Generated by Django 2.0.7 on 2018-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0056_add_song_original_release_date')]

    operations = [
        migrations.AddField(
            model_name='store', name='active', field=models.BooleanField(default=True)
        )
    ]
