# Generated by Django 2.0.7 on 2018-08-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0058_inactivate_groove_music')]

    operations = [
        migrations.AddField(
            model_name='historicalsongfile',
            name='checksum',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='songfile',
            name='checksum',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
