# Generated by Django 2.0.8 on 2018-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0059_add_file_checksum_to_song_file')]

    operations = [
        migrations.AddField(
            model_name='coverart',
            name='checksum',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcoverart',
            name='checksum',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
