# Generated by Django 2.0.6 on 2018-06-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0061_contributor_user_artist_royalty_split')]

    operations = [
        migrations.CreateModel(
            name='ContributorRole',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.SmallIntegerField(
                        choices=[
                            (1, 'primary_artist'),
                            (2, 'featured_artist'),
                            (3, 'writer'),
                            (4, 'producer'),
                            (5, 'mixer'),
                            (6, 'remixer'),
                            (7, 'performer'),
                            (8, 'other'),
                        ]
                    ),
                ),
                (
                    'contributor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Contributor',
                    ),
                ),
            ],
        )
    ]
