# Generated by Django 2.0.8 on 2018-08-28 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0024_artists_data_migration'),
        ('releases', '0064_make_primary_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrelease',
            name='artist',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='users.Artist',
            ),
        ),
        migrations.AddField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='users.Artist',
            ),
        ),
    ]
