# Generated by Django 2.0.8 on 2018-08-06 09:08

import django.core.validators
from django.db import migrations, models


def populate_iso_639_1(apps, schema_editor):
    MetadataLanguage = apps.get_model('releases', 'MetadataLanguage')

    for ml in MetadataLanguage.objects.all():
        if ml.iso_639_1:
            continue

        if ml.fuga_code and len(ml.fuga_code) == 2:
            ml.iso_639_1 = ml.fuga_code
        else:
            if 'Chinese' in ml.name or ml.name == 'Cantonese':
                ml.iso_639_1 = 'zh'
            elif 'Spanish' in ml.name:
                ml.iso_639_1 = 'es'

        ml.save()


class Migration(migrations.Migration):
    dependencies = [('releases', '0066_release_artist_data')]

    operations = [
        migrations.AddField(
            model_name='metadatalanguage',
            name='iso_639_1',
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.RunPython(
            populate_iso_639_1, reverse_code=migrations.RunPython.noop
        ),
    ]
