# Generated by Django 2.0.8 on 2018-09-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0025_invitation'),
        ('releases', '0068_populate_iso_639_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='invitation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='users.Invitation',
            ),
        ),
        migrations.AddField(
            model_name='historicalcontributor',
            name='invitation',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='users.Invitation',
            ),
        ),
    ]
