# Generated by Django 2.0.8 on 2018-10-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0026_lowercase_artist_types'),
        ('releases', '0070_metdata_language_override_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseArtist',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('sequence', models.SmallIntegerField()),
                (
                    'role',
                    models.SmallIntegerField(
                        choices=[(1, 'primary_artist'), (2, 'featured_artist')]
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                (
                    'artist',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='users.Artist',
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='releases.Release',
                    ),
                ),
            ],
        )
    ]
