# Generated by Django 2.0.8 on 2018-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0005_image'),
        ('releases', '0071_contributor_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverart',
            name='images',
            field=models.ManyToManyField(to='amuse.Image'),
        )
    ]
