# Generated by Django 2.0.8 on 2018-11-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0072_coverart_images')]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo_color',
            field=models.URLField(blank=True, max_length=255, null=True),
        )
    ]
