# Generated by Django 2.0.10 on 2019-03-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0073_store_logo_color')]

    operations = [
        migrations.CreateModel(
            name='LyricsAnalysisResult',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('explicit', models.BooleanField()),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'song',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='releases.Song'
                    ),
                ),
            ],
        )
    ]
