# Generated by Django 2.0.10 on 2019-05-16 09:27

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0075_contributor_spotify_id')]

    operations = [
        migrations.AlterField(
            model_name='historicalrelease',
            name='error_flags',
            field=bitfield.models.BitField(
                (
                    ('artwork_social-media', 'Artwork: Social media logos'),
                    ('artwork_text', 'Artwork: Text'),
                    ('artwork_format', 'Artwork: Format'),
                    ('artwork_size', 'Artwork: Size'),
                    ('artwork_blurry', 'Artwork: Blurry'),
                    ('explicit_parental-advisory', 'Explicit: Parental advisory logo'),
                    ('titles_differs', 'Titles differs'),
                    ('release_date-changed', 'Release date changed'),
                    ('release_duplicate', 'Possible duplicate'),
                    ('release_underage', 'Underage'),
                    ('rights_no-rights', 'No Rights'),
                    ('release_generic-artist-name', 'Generic artist name'),
                    ('release_misleading-artist-name', 'Misleadning artist name'),
                    ('artwork_logos-brands', 'Artwork: Logos and brands'),
                    ('artwork_primary-or-featured', 'Artwork: Primary or Featured'),
                    ('artwork_generic', 'Artwork: Generic'),
                    ('artwork_size-new', 'Artwork: Size'),
                    ('artwork_pa-logo-mismatch', 'Artwork: PA mismatch'),
                    ('metadata_symbols-or-emoji', 'Metadata: Symbols/Emojis Error'),
                    (
                        'metadata_symbols-emoji-info',
                        'Metadata: Symbols/Emojis Information',
                    ),
                    ('metadata_generic-terms', 'Metadata: Generic title'),
                    ('compound-artist', 'Compound Artist'),
                ),
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicalsong',
            name='error_flags',
            field=bitfield.models.BitField(
                (
                    ('rights_samplings', 'Contains samplings'),
                    ('rights_remix', 'Remix'),
                    ('rights_no-rights', 'No rights'),
                    ('audio_bad-quality', 'Audio: Bad quality'),
                    ('explicit_lyrics', 'Explicit: Lyrics'),
                    ('genre_not-approved', 'Not approved genre'),
                    ('audio_too-short', 'Audio: Too short'),
                    ('wrong-isrc', 'ISRC Issue'),
                    ('misleading-artist-name', 'Misleadning artist name'),
                    ('audio_silent-end-beginning', 'Audio: Silent end/beginning'),
                    ('audio_cut-short', 'Audio: Cut Short'),
                    ('audio_continuous-mix', 'Audio: Continuous Mix'),
                ),
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='release',
            name='error_flags',
            field=bitfield.models.BitField(
                (
                    ('artwork_social-media', 'Artwork: Social media logos'),
                    ('artwork_text', 'Artwork: Text'),
                    ('artwork_format', 'Artwork: Format'),
                    ('artwork_size', 'Artwork: Size'),
                    ('artwork_blurry', 'Artwork: Blurry'),
                    ('explicit_parental-advisory', 'Explicit: Parental advisory logo'),
                    ('titles_differs', 'Titles differs'),
                    ('release_date-changed', 'Release date changed'),
                    ('release_duplicate', 'Possible duplicate'),
                    ('release_underage', 'Underage'),
                    ('rights_no-rights', 'No Rights'),
                    ('release_generic-artist-name', 'Generic artist name'),
                    ('release_misleading-artist-name', 'Misleadning artist name'),
                    ('artwork_logos-brands', 'Artwork: Logos and brands'),
                    ('artwork_primary-or-featured', 'Artwork: Primary or Featured'),
                    ('artwork_generic', 'Artwork: Generic'),
                    ('artwork_size-new', 'Artwork: Size'),
                    ('artwork_pa-logo-mismatch', 'Artwork: PA mismatch'),
                    ('metadata_symbols-or-emoji', 'Metadata: Symbols/Emojis Error'),
                    (
                        'metadata_symbols-emoji-info',
                        'Metadata: Symbols/Emojis Information',
                    ),
                    ('metadata_generic-terms', 'Metadata: Generic title'),
                    ('compound-artist', 'Compound Artist'),
                ),
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='song',
            name='error_flags',
            field=bitfield.models.BitField(
                (
                    ('rights_samplings', 'Contains samplings'),
                    ('rights_remix', 'Remix'),
                    ('rights_no-rights', 'No rights'),
                    ('audio_bad-quality', 'Audio: Bad quality'),
                    ('explicit_lyrics', 'Explicit: Lyrics'),
                    ('genre_not-approved', 'Not approved genre'),
                    ('audio_too-short', 'Audio: Too short'),
                    ('wrong-isrc', 'ISRC Issue'),
                    ('misleading-artist-name', 'Misleadning artist name'),
                    ('audio_silent-end-beginning', 'Audio: Silent end/beginning'),
                    ('audio_cut-short', 'Audio: Cut Short'),
                    ('audio_continuous-mix', 'Audio: Continuous Mix'),
                ),
                default=None,
                null=True,
            ),
        ),
    ]
