# Generated by Django 2.0.10 on 2019-06-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0039_auto_20190527_1149'),
        ('releases', '0076_release_error_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseArtistRole',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.SmallIntegerField(
                        choices=[(1, 'primary_artist'), (2, 'featured_artist')]
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'artist',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='users.ArtistV2',
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='releases.Release',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SongArtistRole',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.SmallIntegerField(
                        choices=[
                            (1, 'primary_artist'),
                            (2, 'featured_artist'),
                            (3, 'writer'),
                            (4, 'producer'),
                            (5, 'mixer'),
                            (6, 'remixer'),
                            (7, 'performer'),
                            (8, 'other'),
                        ]
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'artist',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='users.ArtistV2',
                    ),
                ),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='releases.Song',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='artists',
            field=models.ManyToManyField(
                through='releases.ReleaseArtistRole', to='users.ArtistV2'
            ),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(
                through='releases.SongArtistRole', to='users.ArtistV2'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='songartistrole', unique_together={('artist', 'song', 'role')}
        ),
        migrations.AlterUniqueTogether(
            name='releaseartistrole', unique_together={('artist', 'release')}
        ),
    ]
