# Generated by Django 2.0.10 on 2019-08-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0077_MUMA_release_artistv2_connection')]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='upc',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='codes.UPC',
            ),
        )
    ]
