# Generated by Django 2.0.10 on 2019-08-29 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0079_make_isrc_field_optional_in_song_model')]

    operations = [
        migrations.RemoveField(model_name='contributor', name='invitation'),
        migrations.RemoveField(model_name='historicalcontributor', name='invitation'),
    ]
