# Generated by Django 2.0.10 on 2019-09-23 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0047_add_hyperwallet_user_and_payment_token_fields'),
        ('releases', '0081_assigning_isrcs_to_all_song_without_it'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltySplit',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'rate',
                    models.DecimalField(
                        decimal_places=4,
                        help_text='A value from 0.0000 to 1.0000',
                        max_digits=5,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'pending'), (1, 'active'), (2, 'canceled')],
                        default=0,
                    ),
                ),
                (
                    'artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='users.ArtistV2'
                    ),
                ),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='releases.Song'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
