# Generated by Django 2.0.10 on 2019-10-11 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0082_royaltysplit')]

    operations = [migrations.RemoveField(model_name='royaltysplit', name='artist')]
