# Generated by Django 2.0.10 on 2019-10-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0083_removing_artist_from_royalty_split_model')]

    operations = [
        migrations.AlterModelOptions(
            name='releaseartistrole', options={'ordering': ['id']}
        ),
        migrations.AlterModelOptions(
            name='songartistrole', options={'ordering': ['id']}
        ),
        migrations.AddField(
            model_name='releaseartistrole',
            name='artist_sequence',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songartistrole',
            name='artist_sequence',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
