# Generated by Django 2.0.10 on 2019-11-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0084_sar_rar_add_artist_sequence')]

    operations = [
        migrations.AddField(
            model_name='releaseartistrole',
            name='main_primary_artist',
            field=models.NullBooleanField(),
        )
    ]
