# Generated by Django 2.0.10 on 2019-12-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0085_releaseartistrole_add_main_primary_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royaltysplit',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'pending'),
                    (1, 'active'),
                    (2, 'canceled'),
                    (3, 'archived'),
                ],
                default=0,
            ),
        ),
    ]
