# Generated by Django 2.0.10 on 2019-12-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0086_adding_archived_as_new_status_for_royalty_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
