# Generated by Django 2.0.10 on 2019-12-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0087_store_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltysplit',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        )
    ]
