# Generated by Django 2.0.10 on 2020-01-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0088_adding_revision_field_to_royalty_split_model')]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Display name for this category', max_length=255
                    ),
                ),
                (
                    'order',
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text='Stores are ordered according to this number',
                    ),
                ),
            ],
            options={'verbose_name_plural': 'Store categories'},
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='releases.StoreCategory',
            ),
        ),
    ]
