# Generated by Django 2.0.10 on 2020-01-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0091_coverart_cdn')]

    operations = [
        migrations.AlterField(
            model_name='royaltysplit',
            name='song',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='royalty_splits',
                to='releases.Song',
            ),
        )
    ]
