# Generated by Django 2.0.10 on 2020-01-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0092_add_related_name')]

    operations = [
        migrations.AlterField(
            model_name='royaltysplit',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'pending'),
                    (1, 'active'),
                    (2, 'canceled'),
                    (3, 'archived'),
                    (4, 'confirmed'),
                ],
                default=0,
            ),
        )
    ]
