# Generated by Django 2.0.10 on 2020-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0093_add_confirmed_status')]

    operations = [
        migrations.AlterField(
            model_name='royaltysplit',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        )
    ]
