# Generated by Django 2.0.10 on 2020-02-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0094_allow_null_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royaltysplit',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'pending'),
                    (1, 'active'),
                    (3, 'archived'),
                    (4, 'confirmed'),
                ],
                default=0,
            ),
        ),
    ]
