# Generated by Django 2.0.10 on 2020-03-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0095_remove_canceled_from_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsong',
            name='preview_start_time',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_start_time',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
