# Generated by Django 2.0.10 on 2020-04-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0096_add_preview_start_time_to_song')]

    operations = [
        migrations.AddField(
            model_name='royaltysplit',
            name='is_owner',
            field=models.BooleanField(default=False),
        )
    ]
