# Generated by Django 2.0.10 on 2020-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("releases", "0097_royaltysplit_is_owner")]

    operations = [
        migrations.CreateModel(
            name="BlacklistedArtistName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
