# Generated by Django 2.0.10 on 2020-05-07 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0098_adding_blacklisted_artist_name_table'),
        ('users', '0070_remove_contributor_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='song',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contributorrole',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='historicalcontributor',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='historicalcontributor',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcontributor',
            name='song',
        ),
        migrations.RemoveField(
            model_name='historicalcontributor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='ContributorRole',
        ),
        migrations.DeleteModel(
            name='HistoricalContributor',
        ),
    ]
