# Generated by Django 2.0.10 on 2020-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0099_remove_contributor_models')]

    operations = [
        migrations.AddField(
            model_name='blacklistedartistname',
            name='fuzzy_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        )
    ]
