# Generated by Django 2.0.13 on 2020-08-20 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0101_royaltysplit_is_locked')]

    operations = [
        migrations.RemoveField(model_name='releaseartist', name='artist'),
        migrations.RemoveField(model_name='releaseartist', name='release'),
        migrations.DeleteModel(name='ReleaseArtist'),
    ]
