# Generated by Django 2.0.13 on 2020-12-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0103_remove_artist_from_releases')]

    operations = [
        migrations.AddField(
            model_name='metadatalanguage',
            name='is_lyrics_language',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metadatalanguage',
            name='is_title_language',
            field=models.BooleanField(default=True),
        ),
    ]
