# Generated by Django 2.0.13 on 2021-01-19 12:06

from django.db import migrations, models


REMOVE_COLLIDING_CONSTRAINT_NAME_SQL = '''
ALTER TABLE "releases_release_excluded_stores" DROP CONSTRAINT "releases_release_stores_release_id_store_id_350869a3_uniq";
DROP INDEX "releases_release_stores_release_id_002d7c6a";
DROP INDEX "releases_release_stores_store_id_8f7f0fed";
'''

ADD_COLLIDING_CONSTRAINT_NAME_SQL = '''
ALTER TABLE "releases_release_excluded_stores" ADD CONSTRAINT releases_release_stores_release_id_store_id_350869a3_uniq UNIQUE ("release_id", "store_id");
CREATE INDEX "releases_release_stores_release_id_002d7c6a" ON "releases_release_excluded_stores" ("release_id");
CREATE INDEX "releases_release_stores_store_id_8f7f0fed" ON "releases_release_excluded_stores" ("store_id");
'''

ADD_NON_COLLIDING_CONSTRAINT_NAME_SQL = '''
ALTER TABLE "releases_release_excluded_stores" ADD CONSTRAINT releases_release_stores_release_id_store_id_350869a4_uniq UNIQUE ("release_id", "store_id");
CREATE INDEX "releases_release_stores_release_id_002d7c6b" ON "releases_release_excluded_stores" ("release_id");
CREATE INDEX "releases_release_stores_store_id_8f7f0fee" ON "releases_release_excluded_stores" ("store_id");
'''

REMOVE_NON_COLLIDING_CONSTRAINT_NAME_SQL = '''
ALTER TABLE "releases_release_excluded_stores" DROP CONSTRAINT "releases_release_stores_release_id_store_id_350869a4_uniq";
DROP INDEX "releases_release_stores_release_id_002d7c6b";
DROP INDEX "releases_release_stores_store_id_8f7f0fee";
'''


class Migration(migrations.Migration):
    dependencies = [('releases', '0104_add_is_lyrics_and_is_title_to_languages')]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='excluded_stores',
            field=models.ManyToManyField(
                blank=True,
                help_text='This is the stores to <strong>exclude</strong> from delivery.',
                related_name='excluded_releases',
                to='releases.Store',
            ),
        ),
        migrations.RunSQL(
            REMOVE_COLLIDING_CONSTRAINT_NAME_SQL, ADD_COLLIDING_CONSTRAINT_NAME_SQL
        ),
        migrations.AddField(
            model_name='release',
            name='stores',
            field=models.ManyToManyField(
                blank=True,
                help_text='Deliver release to these stores',
                to='releases.Store',
            ),
        ),
        migrations.RunSQL(
            ADD_NON_COLLIDING_CONSTRAINT_NAME_SQL,
            REMOVE_NON_COLLIDING_CONSTRAINT_NAME_SQL,
        ),
    ]
