# Generated by Django 2.0.13 on 2021-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0105_release_stores')]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='stores',
            field=models.ManyToManyField(
                blank=True,
                help_text='Deliver release to these stores',
                to='releases.Store',
                verbose_name='Included Stores',
            ),
        )
    ]
