# Generated by Django 2.1.15 on 2021-03-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0107_store_internal_name')]

    operations = [
        migrations.AddField(
            model_name='store',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='releases.Store',
            ),
        )
    ]
