# Generated by Django 2.1.15 on 2021-05-19 13:28

from django.db import migrations, models
import django.db.models.deletion
import releases.models.asset_label


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0110_disallow_blank_artist_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLabel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.TextField(
                        max_length=50,
                        unique=True,
                        validators=[releases.models.asset_label.validate_asset_label],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseAssetLabel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'asset_label',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='releases.AssetLabel',
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='asset_labels',
                        to='releases.Release',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='assetlabel',
            name='releases',
            field=models.ManyToManyField(
                through='releases.ReleaseAssetLabel', to='releases.Release'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='releaseassetlabel',
            unique_together={('release', 'asset_label')},
        ),
    ]
