# Generated by Django 2.1.15 on 2021-05-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0111_release_asset_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongAssetLabel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'asset_label',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='releases.AssetLabel',
                    ),
                ),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='asset_labels',
                        to='releases.Song',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='assetlabel',
            name='songs',
            field=models.ManyToManyField(
                through='releases.SongAssetLabel', to='releases.Song'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='songassetlabel',
            unique_together={('song', 'asset_label')},
        ),
    ]
