# Generated by Django 2.1.15 on 2021-06-18 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0112_song_asset_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseAsset',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('releases.release',),
        ),
    ]
