# Generated by Django 2.1.15 on 2021-07-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0113_releaseasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrelease',
            name='include_pre_save_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='include_pre_save_link',
            field=models.BooleanField(default=False),
        ),
    ]
