# Generated by Django 2.1.15 on 2021-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0114_release_pre_save_link')]

    operations = [
        migrations.AlterField(
            model_name='songartistrole',
            name='role',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'primary_artist'),
                    (2, 'featured_artist'),
                    (3, 'writer'),
                    (4, 'producer'),
                    (5, 'mixer'),
                    (6, 'remixer'),
                ]
            ),
        )
    ]
