# Generated by Django 2.2.25 on 2022-01-24 09:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0115_alter_song_artist_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='extra_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
