# Generated by Django 2.2.25 on 2022-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0117_store_admin_active')]

    operations = [
        migrations.AddField(
            model_name='store',
            name='multi_batch_support',
            field=models.BooleanField(default=True),
        )
    ]
