# Generated by Django 2.2.25 on 2022-06-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0119_add_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hex_color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
