# Generated by Django 2.2.25 on 2022-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0121_add_fugametadata')]

    operations = [
        migrations.AlterField(
            model_name='fugametadata',
            name='product_id',
            field=models.BigIntegerField(unique=True),
        )
    ]
