# Generated by Django 2.2.25 on 2022-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0122_fuga_big_int')]

    operations = [
        migrations.AddField(
            model_name='store',
            name='show_on_top',
            field=models.BooleanField(default=False),
        )
    ]
