# Generated by Django 2.2.25 on 2022-08-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('releases', '0123_store_show_on_top')]

    operations = [
        migrations.CreateModel(
            name='FugaStores',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('external_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('is_iip_dds', models.BooleanField(editable=False)),
                ('is_ssf_dds', models.BooleanField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'verbose_name_plural': 'Fuga Stores'},
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='delivery_history_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FugaDeliveryHistory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('external_id', models.BigIntegerField(unique=True)),
                ('product_id', models.BigIntegerField(db_index=True, editable=False)),
                (
                    'ddex_batch_id',
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    'action',
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    'state',
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    'status',
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    'executed_by',
                    models.CharField(db_index=True, editable=False, max_length=256),
                ),
                ('dated_at', models.DateTimeField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'fuga_store',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.FugaStores',
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Release',
                    ),
                ),
            ],
            options={'verbose_name_plural': 'Fuga Delivery History'},
        ),
    ]
