# Generated by Django 2.2.25 on 2022-08-11 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0124_add_fuga_tables')]

    operations = [
        migrations.RemoveField(model_name='fugadeliveryhistory', name='status')
    ]
