# Generated by Django 3.2.15 on 2022-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0125_remove_fugadeliveryhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fugametadata',
            name='asset_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fugametadata',
            name='delivery_instructions_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fugametadata',
            name='release_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaseartistrole',
            name='main_primary_artist',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='extra_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
