# Generated by Django 3.2.15 on 2022-10-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0127_alter_fugadeliveryhistory_executed_by')]

    operations = [
        migrations.AddField(
            model_name='fugametadata',
            name='added_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='c_line_text',
            field=models.CharField(
                blank=True, editable=False, max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='c_line_year',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='catalog_tier',
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='compilation',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='consumer_release_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='cover_height',
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='cover_width',
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='delete_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='genre',
            field=models.CharField(
                blank=True, editable=False, max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='hashed_key',
            field=models.CharField(
                blank=True, editable=False, max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='label',
            field=models.CharField(
                blank=True, editable=False, max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='language',
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='mark_to_be_deleted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='metadata_match',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='name',
            field=models.CharField(
                blank=True, editable=False, max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='original_release_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='p_line_text',
            field=models.CharField(
                blank=True, editable=False, max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='p_line_year',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='parental_advisory',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='parental_advisory_next',
            field=models.CharField(blank=True, editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='product_type',
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='release_format_type',
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='release_version',
            field=models.CharField(
                blank=True, editable=False, max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='state',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='subgenre',
            field=models.CharField(
                blank=True, editable=False, max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='total_assets',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='upc',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=16, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='whitelisted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
