# Generated by Django 3.2.15 on 2022-10-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0130_add_extra_fuga_tables')]

    operations = [
        migrations.RemoveField(model_name='fugaproductartist', name='primary'),
        migrations.RemoveField(model_name='fugaproductassetartist', name='primary'),
        migrations.AddField(
            model_name='fugaartist',
            name='parsed_at',
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugaartist',
            name='matched_artist',
            field=models.BigIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fugaartisttoperson',
            name='names_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugaartisttoperson',
            name='verified',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
