# Generated by Django 3.2.15 on 2022-10-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0131_update_extra_fuga_tables')]

    operations = [
        migrations.AddField(
            model_name='fugaproductartist',
            name='primary',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugaproductassetartist',
            name='artist_name',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugaproductassetartist',
            name='primary',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
    ]
