# Generated by Django 3.2.15 on 2022-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0132_fuga_add_fields')]

    operations = [
        migrations.AddField(
            model_name='fugaasset',
            name='recording_year',
            field=models.IntegerField(blank=True, editable=False, null=True),
        )
    ]
