# Generated by Django 3.2.15 on 2022-10-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0133_fugaasset_recording_year')]

    operations = [
        migrations.CreateModel(
            name='FugaMismatch',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('release_id', models.BigIntegerField(db_index=True)),
                ('fuga_product_id', models.BigIntegerField(db_index=True)),
                (
                    'fuga_asset_id',
                    models.BigIntegerField(
                        db_index=True, default=None, editable=False, null=True
                    ),
                ),
                (
                    'mismatch_attribute',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    'jarvis_value',
                    models.CharField(
                        blank=True, editable=False, max_length=1024, null=True
                    ),
                ),
                (
                    'fuga_value',
                    models.CharField(
                        blank=True, editable=False, max_length=1024, null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='fugaasset',
            name='metadata_match',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugaasset',
            name='roles_match',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='ready_to_migrate',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='roles_match',
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fugaasset',
            name='display_artist',
            field=models.CharField(
                blank=True, editable=False, max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugaasset',
            name='p_line_year',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
