# Generated by Django 3.2.15 on 2022-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0134_fugametadata_mismatches')]

    operations = [
        migrations.CreateModel(
            name='FugaProductAsset',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('release_id', models.BigIntegerField(db_index=True)),
                ('fuga_product_id', models.BigIntegerField(db_index=True)),
                ('fuga_asset_id', models.BigIntegerField(db_index=True)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(model_name='fugaartist', name='matched_artist'),
        migrations.AddField(
            model_name='fugaproductartist',
            name='matched_artist_id',
            field=models.BigIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fugaproductassetartist',
            name='matched_artist_id',
            field=models.BigIntegerField(db_index=True, default=None, null=True),
        ),
    ]
