# Generated by Django 3.2.15 on 2022-10-31 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('releases', '0135_fuga_artists_update')]

    operations = [
        migrations.AlterModelOptions(
            name='fugamismatch', options={'verbose_name_plural': 'Fuga mismatches'}
        )
    ]
