# Generated by Django 3.2.15 on 2022-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0136_alter_fugamismatch_options')]

    operations = [
        migrations.AddField(
            model_name='fugaproductasset',
            name='matched_song_id',
            field=models.BigIntegerField(db_index=True, default=None, null=True),
        )
    ]
