# Generated by Django 3.2.15 on 2022-11-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0137_fugaproductasset_matched_song_id')]

    operations = [
        migrations.AddField(
            model_name='fugaproductartist',
            name='roles_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugaproductassetartist',
            name='roles_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
