# Generated by Django 3.2.15 on 2022-11-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0138_add_fuga_roles_match')]

    operations = [
        migrations.CreateModel(
            name='FugaGenre',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, editable=False, max_length=120, null=True
                    ),
                ),
                (
                    'matched_genre_id',
                    models.BigIntegerField(db_index=True, default=None, null=True),
                ),
            ],
        )
    ]
