# Generated by Django 3.2.15 on 2022-11-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0139_fugagenre')]

    operations = [
        migrations.AlterField(
            model_name='fugametadata',
            name='metadata_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugametadata',
            name='ready_to_migrate',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugametadata',
            name='roles_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
