# Generated by Django 3.2.15 on 2022-11-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0140_add_fugametadata_indexes')]

    operations = [
        migrations.AddField(
            model_name='fugaproductasset',
            name='metadata_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugaproductasset',
            name='roles_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugaasset',
            name='metadata_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugaasset',
            name='roles_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugaperson',
            name='name',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugaproductassetartist',
            name='primary',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='fugaproductassetartist',
            name='role',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=128, null=True
            ),
        ),
    ]
