# Generated by Django 3.2.15 on 2022-11-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0142_add_fuga_person_for_asset_artist_roles')]

    operations = [
        migrations.AddField(
            model_name='fugaasset',
            name='song_metadata_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugaasset',
            name='song_roles_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
