# Generated by Django 3.2.15 on 2022-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0143_add_fuga_aggregate_flags')]

    operations = [
        migrations.RemoveField(model_name='fugaasset', name='song_metadata_match'),
        migrations.RemoveField(model_name='fugaasset', name='song_roles_match'),
        migrations.AddField(
            model_name='fugametadata',
            name='song_metadata_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='song_roles_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
