# Generated by Django 3.2.15 on 2022-11-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0144_add_fugametdata_flags')]

    operations = [
        migrations.AddField(
            model_name='fugaproductartist',
            name='apple_id',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugaproductartist',
            name='spotify_id',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugaproductassetartist',
            name='apple_id',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugaproductassetartist',
            name='spotify_id',
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=1024, null=True
            ),
        ),
    ]
