# Generated by Django 3.2.15 on 2022-11-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0057_bulkdeliveryjob_ignore_release_status'),
        ('releases', '0145_add_fuga_artist_dsp_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='batch_size',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='store',
            name='fuga_store',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='releases.fugastores',
            ),
        ),
        migrations.CreateModel(
            name='ReleaseStoreDeliveryStatus',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('status', models.CharField(db_index=True, max_length=128)),
                (
                    'verified',
                    models.BooleanField(
                        db_index=True, default=None, editable=False, null=True
                    ),
                ),
                ('dsp_release_id', models.CharField(db_index=True, max_length=1024)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'fuga_store',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.fugastores',
                    ),
                ),
                (
                    'latest_delivery_log',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='amuse.batchdeliveryrelease',
                    ),
                ),
                (
                    'latest_fuga_delivery_log',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='releases.fugadeliveryhistory',
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.release',
                    ),
                ),
                (
                    'store',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.store',
                    ),
                ),
            ],
        ),
    ]
