# Generated by Django 3.2.15 on 2022-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0146_add_release_store_delivery_status')]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='internal_name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        )
    ]
