# Generated by Django 3.2.15 on 2022-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0147_alter_store_internal_name')]

    operations = [
        migrations.AddField(
            model_name='releasestoredeliverystatus',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        )
    ]
