# Generated by Django 3.2.15 on 2022-12-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0149_alter_releasestoredeliverystatus_delivered_at')]

    operations = [
        migrations.AlterField(
            model_name='releasestoredeliverystatus',
            name='dsp_release_id',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        )
    ]
