# Generated by Django 3.2.15 on 2022-12-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0150_alter_releasestoredeliverystatus_dsp_release_id')
    ]

    operations = [
        migrations.AddField(
            model_name='fugaasset',
            name='spotify_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='spotify_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
