# Generated by Django 3.2.15 on 2022-12-14 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0151_add_spotify_metadata')]

    operations = [
        migrations.AddField(
            model_name='metadatalanguage',
            name='iso_639_2',
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        )
    ]
