# Generated by Django 3.2.15 on 2023-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0153_update_with_iso_639_2_codes')]

    operations = [
        migrations.AddField(
            model_name='fugastores',
            name='has_delivery_service_support',
            field=models.BooleanField(default=False, editable=False),
        )
    ]
