# Generated by Django 3.2.15 on 2023-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0154_fugastores_has_delivery_service_support')]

    operations = [
        migrations.AddField(
            model_name='fugametadata',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
