# Generated by Django 3.2.15 on 2023-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0155_fugametadata_last_synced_at')]

    operations = [
        migrations.AddField(
            model_name='fugametadata',
            name='spotify_migration_completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='spotify_migration_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='spotify_ready_to_migrate',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
