# Generated by Django 3.2.15 on 2023-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('releases', '0157_fugametadata_spotify_flags')]

    operations = [
        migrations.AddField(
            model_name='fugametadata',
            name='apple_migration_completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='apple_migration_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='apple_ready_to_migrate',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='apple_roles_match',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='has_alternative_stores',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='has_apple_ids',
            field=models.BooleanField(
                db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='migration_wave',
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name='fugametadata',
            name='revenue_level',
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
