# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-30 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('app', '0001_delivery')]

    operations = [
        migrations.AlterModelOptions(
            name='delivery', options={'verbose_name_plural': 'Deliveries'}
        ),
        migrations.RemoveField(model_name='delivery', name='user'),
        migrations.AlterField(
            model_name='delivery',
            name='batch_job',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'SUBMITTED'), (1, 'SUCCEEDED'), (99, 'FAILED')],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='store',
            field=models.PositiveSmallIntegerField(
                choices=[(3, 'APPLE')], db_index=True
            ),
        ),
    ]
