# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-31 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('app', '0002_delivery_fields')]

    operations = [
        migrations.CreateModel(
            name='NonexistentUser',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'nonexistent_user'},
        )
    ]
