# Generated by Django 3.2.15 on 2023-01-12 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('app', '0004_fix-postgres-error-E003')]

    operations = [migrations.DeleteModel(name='NonexistentUser')]
