# Generated by Django 2.0.10 on 2020-04-07 09:23

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0069_add_expired_status_to_team_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveArtist',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.artistv2',),
        ),
    ]
