# Generated by Django 2.0.10 on 2019-11-20 13:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'external_transaction_id',
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    'customer_payment_payload',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    'external_payment_response',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, help_text='Total amount paid', max_digits=5
                    ),
                ),
                (
                    'currency',
                    models.PositiveSmallIntegerField(choices=[(1, 'USD')], default=1),
                ),
                (
                    'vat_amount',
                    models.DecimalField(
                        decimal_places=2, help_text='VAT part of amount', max_digits=5
                    ),
                ),
                (
                    'country_code',
                    models.CharField(
                        blank=True,
                        help_text='ISO country code for payment, given by the payment provider',
                        max_length=2,
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'not sent'),
                            (1, 'pending'),
                            (2, 'approved'),
                            (3, 'declined'),
                            (4, 'canceled'),
                            (5, 'error'),
                        ],
                        default=0,
                    ),
                ),
                (
                    'provider',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'Adyen'), (2, 'iOS in-app')], default=1
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('valid_from', models.DateField()),
                (
                    'valid_until',
                    models.DateField(
                        blank=True,
                        help_text='Empty means subscription is active, only ended subscriptions have this set',
                        null=True,
                    ),
                ),
                (
                    'external_recurring_id',
                    models.CharField(
                        blank=True,
                        help_text='ID used by payment provider to identify the subscription',
                        max_length=255,
                        null=True,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, help_text='Including VAT', max_digits=5
                    ),
                ),
                (
                    'period',
                    models.IntegerField(
                        blank=True,
                        help_text='Number of months of pro membership granted by this type of subscription. If left blank it is a perpetual subscription.',
                        null=True,
                    ),
                ),
                (
                    'is_public',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='If checked users can see and purchase this subscription',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='payments.SubscriptionPlan',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(
                help_text='If this is unset, it means the subscription payment is not yet authorised by the payment provider',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='payments.Subscription'
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
