# Generated by Django 2.0.10 on 2019-11-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid_from',
            field=models.DateField(db_index=True),
        )
    ]
