# Generated by Django 2.0.10 on 2019-11-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0002_country_region_code'),
        ('payments', '0002_subscription_valid_from_index'),
    ]

    operations = [
        migrations.RemoveField(model_name='paymenttransaction', name='country_code'),
        migrations.AddField(
            model_name='paymenttransaction',
            name='country',
            field=models.ForeignKey(
                default=None,
                help_text='Country for payment, used to determine VAT on receipt',
                on_delete=django.db.models.deletion.PROTECT,
                to='countries.Country',
            ),
            preserve_default=False,
        ),
    ]
