# Generated by Django 2.0.10 on 2019-12-09 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0003_change_country_code_to_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='paid_until',
            field=models.DateField(default=datetime.date(2019, 12, 9)),
            preserve_default=False,
        ),
    ]
