# Generated by Django 2.0.10 on 2019-12-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0004_paymenttransaction_paid_until')]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_summary',
            field=models.CharField(
                blank=True,
                help_text='Last four digits of card',
                max_length=4,
                null=True,
            ),
        ),
    ]
