# Generated by Django 2.0.10 on 2019-12-16 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('payments', '0005_card_details_on_subscription')]

    operations = [
        migrations.RemoveField(model_name='paymenttransaction', name='provider'),
        migrations.AddField(
            model_name='paymenttransaction',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'unknown'), (1, 'payment'), (2, 'authorisation')],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Adyen'), (2, 'iOS in-app')], default=1
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Created'),
                    (1, 'Active'),
                    (2, 'Expired'),
                    (3, 'Pending'),
                    (4, 'Error'),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='valid_until',
            field=models.DateField(
                blank=True,
                help_text='Only ended subscriptions have this set',
                null=True,
            ),
        ),
    ]
