# Generated by Django 2.0.10 on 2019-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0006_add_payments_meta_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(
                default=0,
                help_text='Number of free trial days granted at beginning of subscription',
            ),
        ),
    ]
