# Generated by Django 2.0.10 on 2019-12-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0007_trial_days_for_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='payments.SubscriptionPlan',
            ),
        ),
    ]
