# Generated by Django 2.0.10 on 2020-01-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0009_add_vat_percentage_to_payment_transaction')]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Created'),
                    (1, 'Active'),
                    (2, 'Expired'),
                    (3, 'Pending'),
                    (4, 'Error'),
                    (5, 'Replaced (was never used)'),
                ],
                default=0,
            ),
        )
    ]
