# Generated by Django 2.0.10 on 2020-01-10 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0010_status_replaced_added_to_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
