# Generated by Django 2.0.10 on 2020-01-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0003_rename_subscription_models'),
        ('payments', '0011_delete_subscription_and_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='subscriptions.Subscription',
            ),
            preserve_default=False,
        )
    ]
