# Generated by Django 2.0.10 on 2020-01-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0012_paymenttransaction_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'external_recurring_id',
                    models.CharField(
                        blank=True,
                        help_text='ID used by payment provider to identify the payment method',
                        max_length=255,
                        null=True,
                    ),
                ),
                ('method', models.CharField(blank=True, max_length=4, null=True)),
                (
                    'summary',
                    models.CharField(
                        blank=True,
                        help_text='Last four digits of card',
                        max_length=4,
                        null=True,
                    ),
                ),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
