# Generated by Django 2.0.10 on 2020-03-05 09:02

import django.db.models.deletion
from django.db import migrations, models


SET_PLAN_SQL = '''
UPDATE
    payments_paymenttransaction AS p
SET
    plan_id = s.plan_id
FROM
    subscriptions_subscription AS s
WHERE
    p.subscription_id = s.id
'''


class Migration(migrations.Migration):
    dependencies = [('payments', '0014_change_paid_until_to_datetime_field')]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='subscriptions.SubscriptionPlan',
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(SET_PLAN_SQL, ''),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to='subscriptions.SubscriptionPlan',
            ),
            preserve_default=False,
        ),
    ]
