# Generated by Django 2.0.10 on 2020-03-05 10:08

import django.db.models.deletion
from django.db import migrations, models


SET_PAYMENT_METHOD_SQL = '''
UPDATE
    payments_paymenttransaction AS p
SET
    payment_method_id = s.payment_method_id
FROM
    subscriptions_subscription AS s
WHERE
    p.subscription_id = s.id
'''


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0005_payment_method_model'),
        ('payments', '0015_paymenttransaction_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='payments.PaymentMethod',
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(SET_PAYMENT_METHOD_SQL, ''),
    ]
