# Generated by Django 2.0.10 on 2020-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0016_paymenttransaction_method')]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(blank=True, max_length=16, null=True),
        )
    ]
