# Generated by Django 2.0.10 on 2020-04-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0017_increase_payment_method_method_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='category',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'initial_purchase'),
                    (2, 'renewal'),
                    (3, 'retry'),
                ],
                default=0,
            ),
        ),
    ]
