# Generated by Django 2.0.10 on 2020-05-06 08:49

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0005_set_is_adyen_enabled_and_vat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0011_subscriptionplan_apple_product_id_notrial'),
        ('payments', '0018_paymenttransaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentTransaction',
            fields=[
                (
                    'id',
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name='ID'
                    ),
                ),
                (
                    'external_transaction_id',
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    'customer_payment_payload',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    'external_payment_response',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, help_text='Total amount paid', max_digits=5
                    ),
                ),
                (
                    'currency',
                    models.PositiveSmallIntegerField(choices=[(1, 'USD')], default=1),
                ),
                (
                    'vat_amount',
                    models.DecimalField(
                        decimal_places=2, help_text='VAT part of amount', max_digits=5
                    ),
                ),
                (
                    'vat_percentage',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='VAT percentage of amount',
                        max_digits=5,
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'not sent'),
                            (1, 'pending'),
                            (2, 'approved'),
                            (3, 'declined'),
                            (4, 'canceled'),
                            (5, 'error'),
                        ],
                        default=0,
                    ),
                ),
                ('paid_until', models.DateTimeField()),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'unknown'), (1, 'payment'), (2, 'authorisation')],
                        default=0,
                    ),
                ),
                (
                    'category',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'unknown'),
                            (1, 'initial_purchase'),
                            (2, 'renewal'),
                            (3, 'retry'),
                        ],
                        default=0,
                    ),
                ),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'country',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='countries.Country',
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'payment_method',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='payments.PaymentMethod',
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='subscriptions.SubscriptionPlan',
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='subscriptions.Subscription',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical payment transaction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        )
    ]
