# Generated by Django 2.0.13 on 2020-06-16 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0019_historicalpaymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymenttransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='currency',
        ),
    ]
