# Generated by Django 2.0.13 on 2020-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0020_remove_currency_from_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, help_text='Total amount paid', max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='vat_amount',
            field=models.DecimalField(
                decimal_places=2, help_text='VAT part of amount', max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, help_text='Total amount paid', max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='vat_amount',
            field=models.DecimalField(
                decimal_places=2, help_text='VAT part of amount', max_digits=8
            ),
        ),
    ]
