# Generated by Django 2.0.13 on 2020-09-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0022_paymenttransaction_currency')]

    operations = [
        migrations.AddField(
            model_name='historicalpaymenttransaction',
            name='platform',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'android'),
                    (2, 'ios'),
                    (3, 'web'),
                    (4, 'api'),
                    (5, 'admin'),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='platform',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'android'),
                    (2, 'ios'),
                    (3, 'web'),
                    (4, 'api'),
                    (5, 'admin'),
                ],
                default=0,
            ),
        ),
    ]
