# Generated by Django 2.0.13 on 2020-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0023_paymenttransaction_platform')]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='platform',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'android'),
                    (2, 'ios'),
                    (3, 'web'),
                    (4, 'cron'),
                    (5, 'admin'),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='platform',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'android'),
                    (2, 'ios'),
                    (3, 'web'),
                    (4, 'cron'),
                    (5, 'admin'),
                ],
                default=0,
            ),
        ),
    ]
