# Generated by Django 2.1.15 on 2021-03-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0024_paymenttransaction_rename_platform_api_to_cron')]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'payment'),
                    (2, 'authorisation'),
                    (3, 'free_trial'),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'payment'),
                    (2, 'authorisation'),
                    (3, 'free_trial'),
                ],
                default=0,
            ),
        ),
    ]
