# Generated by Django 2.1.15 on 2021-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('payments', '0025_paymenttransaction_freetrial')]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'payment'),
                    (2, 'authorisation'),
                    (3, 'free_trial'),
                    (4, 'introductory_payment'),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'unknown'),
                    (1, 'payment'),
                    (2, 'authorisation'),
                    (3, 'free_trial'),
                    (4, 'introductory_payment'),
                ],
                default=0,
            ),
        ),
    ]
