# Generated by Django 2.2.25 on 2022-08-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('payments', '0027_paymenttransaction_vat_amount_sek')]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='country',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Country for payment, used to determine VAT on receipt',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='countries.Country',
            ),
        ),
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=5,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='countries.Currency',
            ),
        ),
    ]
