# Generated by Django 3.2.15 on 2022-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0028_changed_country_currency_historicalpaymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='customer_payment_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='external_payment_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='customer_payment_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='external_payment_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
