# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                (
                    'code',
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ('name', models.CharField(max_length=255)),
            ],
        )
    ]
