# Generated by Django 2.0.8 on 2018-11-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('countries', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        )
    ]
