# Generated by Django 2.0.13 on 2020-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0005_set_is_adyen_enabled_and_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                (
                    'decimals',
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text='Number of decimals used when performing Adyen transactions',
                    ),
                ),
            ],
        ),
    ]
