# Generated by Django 2.0.13 on 2020-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0006_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'rate',
                    models.DecimalField(
                        decimal_places=10,
                        help_text='Exchange rate from currency to EUR',
                        max_digits=12,
                    ),
                ),
                ('year', models.PositiveSmallIntegerField()),
                (
                    'quarter',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4)]
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=models.RESTRICT, to='countries.Currency'
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency', 'year', 'quarter')},
        ),
    ]
