# Generated by Django 2.1.15 on 2021-09-21 20:42
import django.core.validators
from django.db import migrations, models

import countries.models


class Migration(migrations.Migration):
    dependencies = [('countries', '0007_exchange_rate')]

    operations = [
        migrations.AddField(
            model_name='country',
            name='internal_numeric_code',
            field=models.SmallIntegerField(
                help_text='Value used internally by Amuse', null=True
            ),
        ),
        migrations.AlterField(
            model_name='country',
            name='internal_numeric_code',
            field=models.SmallIntegerField(
                default=countries.models.next_internal_numeric_code,
                help_text='Value used internally by Amuse',
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(255),
                ],
            ),
        ),
    ]
