# Generated by Django 2.2.25 on 2022-02-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0009_countires_add_hw_enabled_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.PositiveSmallIntegerField(
                help_text='Country calling code', null=True
            ),
        ),
        migrations.AddField(
            model_name='country',
            name='is_yt_content_id_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Is You Tube Content ID allowed for this country',
            ),
        ),
    ]
