# Generated by Django 2.2.25 on 2022-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('countries', '0010_add_dial_code_and_is_yt_content_id_enabled')]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='dial_code',
            field=models.PositiveSmallIntegerField(
                blank=True, help_text='Country calling code', null=True
            ),
        )
    ]
