# Generated by Django 2.2.25 on 2022-07-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('countries', '0011_dial_code_set_blank_true')]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_signup_enabled',
            field=models.BooleanField(
                default=True, help_text='Enable signups for this country'
            ),
        )
    ]
