# Generated by Django 2.0.10 on 2020-01-09 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSubscription',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('valid_from', models.DateField(db_index=True)),
                (
                    'valid_until',
                    models.DateField(
                        blank=True,
                        help_text='Only ended subscriptions have this set',
                        null=True,
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'Created'),
                            (1, 'Active'),
                            (2, 'Expired'),
                            (3, 'Pending'),
                            (4, 'Error'),
                            (5, 'Replaced (was never used)'),
                        ],
                        default=0,
                    ),
                ),
                (
                    'provider',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'Adyen'), (2, 'iOS in-app')], default=1
                    ),
                ),
                (
                    'external_recurring_id',
                    models.CharField(
                        blank=True,
                        help_text='ID used by payment provider to identify the subscription',
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    'payment_method',
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    'payment_summary',
                    models.CharField(
                        blank=True,
                        help_text='Last four digits of card',
                        max_length=4,
                        null=True,
                    ),
                ),
                ('payment_expiry_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewSubscriptionPlan',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, help_text='Including VAT', max_digits=5
                    ),
                ),
                (
                    'period',
                    models.IntegerField(
                        blank=True,
                        help_text='Number of months of pro membership granted by this type of subscription. If left blank it is a perpetual subscription.',
                        null=True,
                    ),
                ),
                (
                    'trial_days',
                    models.IntegerField(
                        default=0,
                        help_text='Number of free trial days granted at beginning of subscription',
                    ),
                ),
                (
                    'is_public',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='If checked users can see and purchase this subscription',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='newsubscription',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='subscriptions.NewSubscriptionPlan',
            ),
        ),
        migrations.AddField(
            model_name='newsubscription',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
