# Generated by Django 2.0.10 on 2020-01-10 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='newsubscription',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
