# Generated by Django 2.0.10 on 2020-01-10 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_subscriptions_related_name_for_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewSubscription',
            new_name='Subscription',
        ),
        migrations.RenameModel(
            old_name='NewSubscriptionPlan',
            new_name='SubscriptionPlan',
        ),
    ]
