# Generated by Django 2.0.10 on 2020-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0003_rename_subscription_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
