# Generated by Django 2.0.10 on 2020-01-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0013_paymentmethod'),
        ('subscriptions', '0004_subscriptionplan_apple_product_id'),
    ]

    operations = [
        migrations.RemoveField(model_name='subscription', name='external_recurring_id'),
        migrations.RemoveField(model_name='subscription', name='payment_expiry_date'),
        migrations.RemoveField(model_name='subscription', name='payment_summary'),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='payments.PaymentMethod',
            ),
        ),
    ]
