# Generated by Django 2.0.10 on 2020-01-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0006_subscriptionplan_grace_period_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Created (pending first payment)'),
                    (1, 'Active'),
                    (2, 'Expired (was not renewed or was canceled)'),
                    (
                        3,
                        'Pending (waiting for currently active subscription to expire)',
                    ),
                    (4, 'Error (first payment failed)'),
                    (5, 'Canceled (was replaced by other subscription)'),
                    (6, 'In expiry grace period (due to failed payment)'),
                ],
                default=0,
            ),
        ),
    ]
