# Generated by Django 2.0.10 on 2020-01-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0007_update_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
