# Generated by Django 2.0.10 on 2020-01-22 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0008_subscription_trial_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='trial_expiration_date',
        ),
    ]
