# Generated by Django 2.0.10 on 2020-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0009_remove_subscription_trial_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Created (pending first payment)'),
                    (1, 'Active'),
                    (2, 'Expired (was not renewed or was canceled)'),
                    (4, 'Error (first payment failed)'),
                    (6, 'In expiry grace period (due to failed payment)'),
                ],
                default=0,
            ),
        ),
    ]
