# Generated by Django 2.0.10 on 2020-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0010_remove_unused_statuses')]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id_notrial',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Users that are not eligible for trial will be put on this plan',
                max_length=255,
            ),
        )
    ]
