# Generated by Django 2.0.13 on 2020-06-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0006_currency'),
        ('subscriptions', '0012_historicalsubscription_historicalsubscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='countries.Currency',
            ),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='countries',
            field=models.ManyToManyField(blank=True, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='countries.Currency',
            ),
        ),
    ]
