# Generated by Django 2.0.13 on 2020-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0013_add_country_currency_to_sub_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='price',
            field=models.DecimalField(
                decimal_places=2, help_text='Including VAT', max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(
                decimal_places=2, help_text='Including VAT', max_digits=8
            ),
        ),
    ]
