# Generated by Django 2.0.13 on 2020-07-15 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0016_pricecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionplan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='historicalsubscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
    ]
