# Generated by Django 2.0.13 on 2020-12-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0017_deprecate_plan_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='tier',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Amuse PLUS subscription tier'),
                    (2, 'Amuse PRO subscription tier'),
                ],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Amuse PLUS subscription tier'),
                    (2, 'Amuse PRO subscription tier'),
                ],
                default=2,
            ),
        ),
    ]
