# Generated by Django 2.0.13 on 2021-01-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0019_add_google_product_id_column')]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscription',
            name='provider',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Adyen'), (2, 'iOS in-app'), (3, 'Google in-app')],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Adyen'), (2, 'iOS in-app'), (3, 'Google in-app')],
                default=1,
            ),
        ),
    ]
