# Generated by Django 2.1.15 on 2021-02-05 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0020_add_google_subscription_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanChanges',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'completed',
                    models.BooleanField(
                        default=False,
                        help_text='Set to True once plan change is completed',
                    ),
                ),
                (
                    'valid',
                    models.BooleanField(
                        default=True, help_text='Used to invalidate plan change'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'current_plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='current_plans',
                        to='subscriptions.SubscriptionPlan',
                    ),
                ),
                (
                    'new_plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='new_plans',
                        to='subscriptions.SubscriptionPlan',
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='plan_changes',
                        to='subscriptions.Subscription',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplanchanges',
            unique_together={('subscription', 'current_plan', 'new_plan')},
        ),
    ]
