# Generated by Django 2.1.15 on 2021-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0021_sub-plan-changes-table')]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='free_trial_from',
            field=models.DateField(
                blank=True,
                help_text="Free Trial start date. Always used in pair with 'Free Trial Until'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='free_trial_until',
            field=models.DateField(
                blank=True,
                help_text="Free Trial start date. Always used in pair with 'Free Trial From'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='free_trial_from',
            field=models.DateField(
                blank=True,
                help_text="Free Trial start date. Always used in pair with 'Free Trial Until'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='free_trial_until',
            field=models.DateField(
                blank=True,
                help_text="Free Trial start date. Always used in pair with 'Free Trial From'.",
                null=True,
            ),
        ),
    ]
