# Generated by Django 2.1.15 on 2021-03-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0022_subscription_free_trial_dates')]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscription',
            name='free_trial_from',
            field=models.DateTimeField(
                blank=True,
                help_text="Free Trial start date. Always used in pair with 'Free Trial Until'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='free_trial_until',
            field=models.DateTimeField(
                blank=True,
                help_text="Free Trial start date. Always used in pair with 'Free Trial From'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='free_trial_from',
            field=models.DateTimeField(
                blank=True,
                help_text="Free Trial start date. Always used in pair with 'Free Trial Until'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='free_trial_until',
            field=models.DateTimeField(
                blank=True,
                help_text="Free Trial start date. Always used in pair with 'Free Trial From'.",
                null=True,
            ),
        ),
    ]
