# Generated by Django 2.1.15 on 2021-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0024_subscriptionplan_google_product_id_notrial')
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='google_product_id_trial',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Users that are eligible for trial will be put on this plan',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='google_product_id_trial',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Users that are eligible for trial will be put on this plan',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='google_product_id_notrial',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Users that are not eligible for trial will be put on this plan. Depracated. Will remove in next PR',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='google_product_id_notrial',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Users that are not eligible for trial will be put on this plan. Depracated. Will remove in next PR',
                max_length=255,
            ),
        ),
    ]
