# Generated by Django 2.1.15 on 2021-05-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0007_exchange_rate'),
        ('subscriptions', '0026_subscriptionplan_remove_gooogle_product_id_notrial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductoryPriceCard',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Discounted price (Including VAT)',
                        max_digits=8,
                    ),
                ),
                (
                    'period_days',
                    models.PositiveSmallIntegerField(
                        default=365,
                        help_text="New subscribers pay a introductory price for a specific duration. After this, they'll pay your regular price.",
                    ),
                ),
                (
                    'start_date',
                    models.DateField(
                        help_text='Introductory Price is available from this date.'
                    ),
                ),
                (
                    'end_date',
                    models.DateField(
                        help_text='Introductory Price is available until this date.'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'countries',
                    models.ManyToManyField(blank=True, to='countries.Country'),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='countries.Currency',
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='subscriptions.SubscriptionPlan',
                    ),
                ),
            ],
        )
    ]
