# Generated by Django 2.1.15 on 2021-05-24 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0027_introductorypricecard')]

    operations = [
        migrations.RemoveField(model_name='introductorypricecard', name='countries'),
        migrations.RemoveField(model_name='introductorypricecard', name='currency'),
        migrations.RemoveField(model_name='introductorypricecard', name='plan'),
        migrations.DeleteModel(name='IntroductoryPriceCard'),
    ]
