# Generated by Django 2.1.15 on 2021-05-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0028_drop_introductorypricecard')]

    operations = [
        migrations.CreateModel(
            name='IntroductoryPriceCard',
            fields=[
                (
                    'pricecard_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='subscriptions.PriceCard',
                    ),
                ),
                (
                    'period',
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="New subscribers pay a introductory price for a specific duration (months). After this, they'll pay your regular price.",
                    ),
                ),
                (
                    'start_date',
                    models.DateField(
                        help_text='Introductory Price is available from this date.'
                    ),
                ),
                (
                    'end_date',
                    models.DateField(
                        help_text='Introductory Price is available until this date.'
                    ),
                ),
            ],
            bases=('subscriptions.pricecard',),
        )
    ]
