# Generated by Django 2.1.15 on 2021-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0030_add_introductory_google_plan')]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='apple_product_id_introductory',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Users that are eligible for introductory offers will be put on this plan',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id_introductory',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Users that are eligible for introductory offers will be put on this plan',
                max_length=255,
            ),
        ),
    ]
