# Generated by Django 2.2.25 on 2022-01-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('subscriptions', '0031_add_introductory_apple_plan')]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscription',
            name='provider',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Adyen'),
                    (2, 'iOS in-app'),
                    (3, 'Google in-app'),
                    (4, 'VIP'),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Adyen'),
                    (2, 'iOS in-app'),
                    (3, 'Google in-app'),
                    (4, 'VIP'),
                ],
                default=1,
            ),
        ),
    ]
