# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('codes', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='isrc',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='upc',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
