# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-17 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('codes', '0002_unique_code_field')]

    operations = [
        migrations.AlterField(
            model_name='isrc',
            name='status',
            field=models.SmallIntegerField(
                choices=[(0, 'Unused'), (1, 'Used'), (2, 'Orphaned')], default=0
            ),
        ),
        migrations.AlterField(
            model_name='upc',
            name='status',
            field=models.SmallIntegerField(
                choices=[(0, 'Unused'), (1, 'Used'), (2, 'Orphaned')], default=0
            ),
        ),
    ]
