# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                ('artist_name', models.CharField(max_length=120)),
                (
                    'email',
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True, unique=True
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    'place_id',
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    'facebook_id',
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True, unique=True
                    ),
                ),
                (
                    'google_id',
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True, unique=True
                    ),
                ),
                (
                    'profile_link',
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        )
    ]
