# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0002_tigocashnumber')]

    operations = [
        migrations.AlterField(
            model_name='tigocashnumber',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='tigo_cash_number',
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
