# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0003_tigocashnumber_2')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
