# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-09 08:32
from __future__ import unicode_literals

from django.db import migrations
from amuse.places import get_country_by_place_id


def populate_country_language(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        if not user.place_id or user.place_id == '':
            continue
        user.country = get_country_by_place_id(user.place_id)
        user.save()


class Migration(migrations.Migration):
    dependencies = [('users', '0004_users_country_language')]

    operations = [migrations.RunPython(populate_country_language)]
