# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0005_populate_country_language')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zendesk_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        )
    ]
