# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0007_comments')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        )
    ]
