# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-24 13:29
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('codes', '0002_unique_code_field'),
        ('users', '0008_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[(1, 'Pending'), (2, 'Completed')]
                    ),
                ),
                (
                    'type',
                    models.SmallIntegerField(
                        choices=[(1, 'Deposit'), (2, 'Withdrawal')]
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=12,
                        default=Decimal('0.0'),
                        help_text='Remember to prefix with minus sign (-) when manually creating a withdrawal transaction.',
                        max_digits=22,
                    ),
                ),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ('date',)},
        ),
        migrations.CreateModel(
            name='TransactionDeposit',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=12, default=Decimal('0.0'), max_digits=22
                    ),
                ),
                (
                    'isrc',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='codes.ISRC'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed')],
                        default=1,
                    ),
                ),
                ('type', models.SmallIntegerField(choices=[(1, 'Fuga')])),
                (
                    'date',
                    models.DateField(
                        help_text='Date to user for transaction deposit date.'
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        storage=storages.backends.s3boto3.S3Boto3Storage(
                            bucket_name=settings.AWS_TRANSACTION_FILE_BUCKET_NAME
                        ),
                        upload_to=users.models.transaction_file_upload_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSource',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionWithdrawal',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                (
                    'transaction',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='withdrawal',
                        serialize=False,
                        to='users.Transaction',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='transactiondeposit',
            name='transaction',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='deposits',
                to='users.Transaction',
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='users.TransactionSource',
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='transactiondeposit', unique_together=set([('transaction', 'isrc')])
        ),
        migrations.AlterUniqueTogether(
            name='transaction', unique_together=set([('date', 'source', 'user')])
        ),
    ]
