# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0009_transactions')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        )
    ]
