# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-01-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0012_migrate_name')]

    operations = [
        migrations.AlterField(
            model_name='user', name='first_name', field=models.CharField(max_length=255)
        ),
        migrations.AlterField(
            model_name='user', name='last_name', field=models.CharField(max_length=255)
        ),
    ]
