# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-01-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0013_user_names_not_nullable')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Default'),
                    (1, 'Flagged'),
                    (2, 'Priority'),
                    (3, 'Qualified'),
                ],
                default=0,
            ),
        )
    ]
