# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-30 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('users', '0016_social_channels')]

    operations = [
        migrations.RemoveField(model_name='tigocashnumber', name='user'),
        migrations.DeleteModel(name='TigoCashNumber'),
    ]
