# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-02-01 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0017_remove_tigocash')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        )
    ]
