# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


def populate_user_email(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for u in User.objects.filter(models.Q(email__isnull=True) | models.Q(email='')):
        u.email = 'changeme-{}@example.com'.format(u.id)
        u.save()


class Migration(migrations.Migration):
    dependencies = [('users', '0018_user_apple_id')]

    operations = [
        migrations.RunPython(
            populate_user_email, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=120, blank=False, null=False, unique=True
            ),
        ),
    ]
