# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0020_auto_20180419_1228')]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'deposit'), (2, 'withdrawal')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'pending'), (2, 'completed')]),
        ),
    ]
