# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-18 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0021_transaction_type_name')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False),
        )
    ]
