# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-30 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0022_user_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'image',
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    'spotify_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'twitter_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'facebook_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'instagram_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'soundcloud_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'youtube_channel',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistMembership',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'Admin'), (2, 'Member')], default=1
                    ),
                ),
                ('created', models.DateField(auto_now_add=True)),
                (
                    'artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='users.Artist'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='members',
            field=models.ManyToManyField(
                through='users.ArtistMembership', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='artist',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
