# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-05-30 12:06
from __future__ import unicode_literals

from django.db import migrations


def create_artists(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Artist = apps.get_model('users', 'Artist')
    for u in User.objects.all():
        a = Artist.objects.create(
            name=u.artist_name,
            spotify_page=u.spotify_page,
            twitter_name=u.twitter_name,
            facebook_page=u.facebook_page,
            instagram_name=u.instagram_name,
            soundcloud_page=u.soundcloud_page,
            youtube_channel=u.youtube_channel,
        )
        # Connect user to Artist
        u.artistmembership_set.create(artist=a)


class Migration(migrations.Migration):
    dependencies = [('users', '0023_artists')]

    operations = [
        migrations.RunPython(create_artists, reverse_code=migrations.RunPython.noop)
    ]
