# Generated by Django 2.0.8 on 2018-09-06 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools


class Migration(migrations.Migration):
    dependencies = [('users', '0024_artists_data_migration')]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_sent', models.DateTimeField(null=True)),
                ('accepted', models.DateTimeField(null=True)),
                (
                    'token',
                    models.CharField(
                        default=functools.partial(
                            django.utils.crypto.get_random_string, *(64,), **{}
                        ),
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    'invitee',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='invitations_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'inviter',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='invitations_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invitation', unique_together={('inviter', 'email')}
        ),
    ]
