# Generated by Django 2.0.8 on 2018-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0025_invitation')]

    operations = [
        migrations.AlterField(
            model_name='artistmembership',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'admin'), (2, 'member')], default=1
            ),
        )
    ]
