# Generated by Django 2.0.8 on 2018-10-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0026_lowercase_artist_types')]

    operations = [
        migrations.AddField(
            model_name='transactionwithdrawal',
            name='verified',
            field=models.NullBooleanField(),
        )
    ]
