# Generated by Django 2.0.8 on 2018-10-25 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0071_releaseartist'),
        ('users', '0028_transactionwithdrawal_verified_default_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contributor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transactions',
                to='releases.Contributor',
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transactions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
