# Generated by Django 2.0.8 on 2018-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0029_transaction_contributor')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artist_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        )
    ]
