# Generated by Django 2.0.8 on 2018-10-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0030_user_optional_artist_name')]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='licensed',
            field=models.NullBooleanField(default=False),
        )
    ]
