# Generated by Django 2.0.8 on 2018-11-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0071_contributor_sort_order'),
        ('users', '0031_transaction_licensed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsource',
            name='store',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='releases.Store',
            ),
        )
    ]
