# Generated by Django 2.0.8 on 2018-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0032_transactionsource_store')]

    operations = [
        migrations.AddField(
            model_name='transactionwithdrawal',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionwithdrawal',
            name='identification_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionwithdrawal',
            name='payee_type',
            field=models.TextField(
                blank=True,
                choices=[('person', 'Person'), ('company', 'Company')],
                null=True,
            ),
        ),
    ]
