# Generated by Django 2.0.8 on 2018-12-12 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0033_payeeinformation')]

    operations = [
        migrations.CreateModel(
            name='RoyaltyAdvance',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'active'),
                            (2, 'denied'),
                            (3, 'submitted'),
                            (4, 'finished'),
                        ],
                        default=1,
                    ),
                ),
                (
                    'advance_amount',
                    models.DecimalField(decimal_places=2, max_digits=22),
                ),
                (
                    'commission_amount',
                    models.DecimalField(decimal_places=2, max_digits=22),
                ),
                (
                    'commission_rate',
                    models.DecimalField(decimal_places=1, max_digits=2),
                ),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                (
                    'identification_number',
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('transactions', models.ManyToManyField(to='users.Transaction')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='royalty_advances',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
