# Generated by Django 2.0.8 on 2018-12-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0034_royaltyadvance')]

    operations = [
        migrations.AddField(
            model_name='royaltyadvance',
            name='label',
            field=models.CharField(default='new', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='royaltyadvance',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'created'),
                    (1, 'active'),
                    (2, 'submitted'),
                    (3, 'cancelled'),
                ],
                default=0,
            ),
        ),
    ]
