# Generated by Django 2.0.8 on 2019-01-31 19:19
import pathlib

from django.db import migrations


def get_contents(file):
    absolute_src_path = pathlib.Path(__file__).parent.parent.parent.resolve()
    with open(f"{absolute_src_path}/{file}") as f:
        return f.read()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0035_royaltyadvance_status'),
        ('codes', '0004_isrc_licensed'),
    ]

    operations = [
        migrations.RunSQL(
            [get_contents("amuse/sql/functions/create_user_transactions_v3.sql")],
            [get_contents("amuse/sql/functions/drop_user_transactions_v3.sql")],
        )
    ]
