# Generated by Django 2.0.10 on 2019-02-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0036_transactions_sql_function')]

    operations = [
        migrations.AlterField(
            model_name='royaltyadvance',
            name='commission_rate',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        )
    ]
