# Generated by Django 2.0.10 on 2019-05-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0038_user_spotify_id')]

    operations = [
        migrations.CreateModel(
            name='ArtistV2',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'image',
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    'spotify_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'twitter_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'facebook_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'instagram_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'soundcloud_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'youtube_channel',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('apple_id', models.CharField(blank=True, max_length=120, null=True)),
                ('spotify_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserArtistRole',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'admin'),
                            (2, 'member'),
                            (3, 'owner'),
                            (4, 'spectator'),
                        ],
                        default=1,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='users.ArtistV2'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='artistv2',
            name='users',
            field=models.ManyToManyField(
                related_name='artists',
                through='users.UserArtistRole',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='userartistrole', unique_together={('user', 'artist')}
        ),
    ]
