# Generated by Django 2.0.10 on 2019-07-24 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0040_MUMA_allow_artistv2_null_owner')]

    operations = [
        migrations.CreateModel(
            name='MinfraudResult',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('response_body', models.TextField()),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('event_time', models.DateTimeField()),
                (
                    'event_type',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'Default'),
                            (1, 'account_creation'),
                            (2, 'account_login'),
                            (3, 'email_change'),
                            (4, 'password_reset'),
                            (5, 'payout_change'),
                            (6, 'purchase'),
                            (7, 'recurring_purchase'),
                            (8, 'referral'),
                            (9, 'survey'),
                        ],
                        default=0,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
