# Generated by Django 2.0.10 on 2019-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0041_minfraudresult')]

    operations = [
        migrations.AlterField(
            model_name='minfraudresult',
            name='event_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Default'),
                    (1, 'Account creation'),
                    (2, 'Release'),
                    (3, 'Email change'),
                    (4, 'Password reset'),
                ],
                default=0,
            ),
        )
    ]
