# Generated by Django 2.0.10 on 2019-08-29 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0080_auto_20190829_0754'),
        ('users', '0043_remove_minfraud_result'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='invitation', unique_together=set()),
        migrations.RemoveField(model_name='invitation', name='invitee'),
        migrations.RemoveField(model_name='invitation', name='inviter'),
        migrations.DeleteModel(name='Invitation'),
    ]
