# Generated by Django 2.0.10 on 2019-08-30 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0044_auto_20190829_0754')]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=120)),
                ('token', models.CharField(max_length=512)),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'pending'), (2, 'accepted'), (3, 'declined')],
                        default=1,
                    ),
                ),
                ('royalty_split', models.BooleanField()),
                ('last_sent', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='users.ArtistV2',
                    ),
                ),
                (
                    'inviter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='invitations_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invitation', unique_together={('inviter', 'artist')}
        ),
    ]
