# Generated by Django 2.0.10 on 2019-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0045_auto_20190830_0944')]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        )
    ]
