# Generated by Django 2.0.10 on 2019-09-30 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0047_add_hyperwallet_user_and_payment_token_fields')]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=120)),
                ('token', models.CharField(max_length=512, unique=True)),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'pending'), (2, 'accepted'), (3, 'declined')],
                        default=1,
                    ),
                ),
                (
                    'team_role',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'admin'),
                            (2, 'member'),
                            (3, 'owner'),
                            (4, 'spectator'),
                        ]
                    ),
                ),
                ('last_sent', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='users.ArtistV2',
                    ),
                ),
                (
                    'invitee',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='team_invitations_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'inviter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='team_invitations_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
