# Generated by Django 2.0.10 on 2019-10-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0048_teaminvitation'), ('releases', '0082_royaltysplit')]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='royalty_split',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='releases.RoyaltySplit',
            ),
        )
    ]
