# Generated by Django 2.0.10 on 2019-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0049_royalty_split_fk_on_invitation')]

    operations = [
        migrations.AlterField(
            model_name='userartistrole',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'admin'),
                    (2, 'member'),
                    (3, 'owner'),
                    (4, 'spectator'),
                    (5, 'superadmin'),
                ],
                default=1,
            ),
        )
    ]
