# Generated by Django 2.0.10 on 2019-10-10 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0082_royaltysplit'),
        ('users', '0050_add_superadmin_to_uar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyInvitation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'created'),
                            (2, 'pending'),
                            (3, 'accepted'),
                            (4, 'declined'),
                        ],
                        default=1,
                    ),
                ),
                ('email', models.EmailField(max_length=120, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=120)),
                ('token', models.CharField(max_length=512, null=True, unique=True)),
                ('last_sent', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'invitee',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='royalty_invitations_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'inviter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='royalty_invitations_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'royalty_split',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='releases.RoyaltySplit',
                    ),
                ),
            ],
        )
    ]
