# Generated by Django 2.0.10 on 2019-10-16 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('users', '0051_royaltyinvitation')]

    operations = [
        migrations.AlterUniqueTogether(name='invitation', unique_together=set()),
        migrations.RemoveField(model_name='invitation', name='artist'),
        migrations.RemoveField(model_name='invitation', name='inviter'),
        migrations.RemoveField(model_name='invitation', name='royalty_split'),
        migrations.DeleteModel(name='Invitation'),
    ]
