# Generated by Django 2.0.10 on 2019-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0052_remove_invitation')]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        )
    ]
