# Generated by Django 2.0.10 on 2019-10-23 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0084_sar_rar_add_artist_sequence'),
        ('users', '0053_teaminvitation_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongArtistInvitation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=120)),
                (
                    'phone_number',
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ('token', models.CharField(max_length=512, unique=True)),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(2, 'pending'), (3, 'accepted'), (4, 'declined')],
                        default=2,
                    ),
                ),
                ('last_sent', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='users.ArtistV2',
                    ),
                ),
                (
                    'invitee',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='song_invitations_accepted',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'inviter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='song_invitations_sent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='song_invitations',
                        to='releases.Song',
                    ),
                ),
            ],
        )
    ]
