# Generated by Django 2.0.10 on 2019-11-05 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0055_user_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArtistV2',
            fields=[
                (
                    'id',
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'image',
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    'spotify_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'twitter_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'facebook_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'instagram_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'soundcloud_page',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'youtube_channel',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('apple_id', models.CharField(blank=True, max_length=120, null=True)),
                ('spotify_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical artist v2',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
