# Generated by Django 2.0.10 on 2019-11-05 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0056_historicalartistv2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
