# Generated by Django 2.0.10 on 2019-11-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0057_rename_is_admin_to_is_staff')]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
