# Generated by Django 2.0.10 on 2019-11-06 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('users', '0058_add_first_last_names_to_team_invitation')]

    operations = [migrations.RemoveField(model_name='user', name='subscription')]
