# Generated by Django 2.0.10 on 2019-12-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0060_make_team_invitation_email_optional')]

    operations = [
        migrations.CreateModel(
            name='UserGDPR',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('minfraud_entries', models.BooleanField(default=False)),
                ('artist_v2_history_entries', models.BooleanField(default=False)),
                ('user_history_entries', models.BooleanField(default=False)),
                ('email_adress', models.BooleanField(default=False)),
                ('user_first_name', models.BooleanField(default=False)),
                ('user_last_name', models.BooleanField(default=False)),
                ('user_social_links', models.BooleanField(default=False)),
                ('user_artist_name', models.BooleanField(default=False)),
                ('artist_v2_names', models.BooleanField(default=False)),
                ('artist_v2_social_links', models.BooleanField(default=False)),
                ('artist_v1_names', models.BooleanField(default=False)),
                ('artist_v1_social_links', models.BooleanField(default=False)),
                ('transaction_withdrawals', models.BooleanField(default=False)),
                ('user_isactive_deactivation', models.BooleanField(default=False)),
                ('user_newsletter_deactivation', models.BooleanField(default=False)),
                (
                    'initiator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='usergdpr_initiator',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='usergdpr_user',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'GDPR Removal',
                'verbose_name_plural': 'GDPR Removals',
            },
        )
    ]
