# Generated by Django 2.0.10 on 2020-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0062_add_spotify_image_to_artistv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='pro_trial_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
