# Generated by Django 2.0.10 on 2020-02-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0063_usermetadata_pro_trial_expiration_date')]

    operations = [
        migrations.AlterField(
            model_name='royaltyinvitation',
            name='royalty_split',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='releases.RoyaltySplit'
            ),
        )
    ]
