# Generated by Django 2.0.10 on 2020-02-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0064_cascade_delete_royalty_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistv2',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artistv2',
            name='spotify_id',
            field=models.CharField(
                blank=True, db_index=True, max_length=120, null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalartistv2',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalartistv2',
            name='spotify_id',
            field=models.CharField(
                blank=True, db_index=True, max_length=120, null=True
            ),
        ),
    ]
