# Generated by Django 2.0.10 on 2020-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0065_artist_v2_add_indices')]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='apple_receipt',
            field=models.TextField(default=''),
        )
    ]
