# Generated by Django 2.0.10 on 2020-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0066_usermetadata_apple_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='apple_receipt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
