# Generated by Django 2.0.10 on 2020-04-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0067_auto_20200318_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='userartistrole',
            name='main_artist_profile',
            field=models.NullBooleanField(default=False),
        ),
    ]
