# Generated by Django 2.0.10 on 2020-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0068_userartistrole_main_artist_profile')]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'pending'),
                    (2, 'accepted'),
                    (3, 'declined'),
                    (4, 'expired'),
                ],
                default=1,
            ),
        )
    ]
