# Generated by Django 2.0.10 on 2020-04-30 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0069_add_expired_status_to_team_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='contributor',
        ),
    ]
