# Generated by Django 2.0.10 on 2020-05-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0070_remove_contributor_fk')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Freeze'),
        )
    ]
