# Generated by Django 2.0.10 on 2020-05-13 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0071_user_is_frozen')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Enable 2FA for user, requires verified phone number',
            ),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='unverified_phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='OtpDevice',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('phone', models.CharField(max_length=120, db_index=True)),
                ('otp_secret', models.CharField(blank=True, max_length=16)),
                ('otp_counter', models.PositiveIntegerField(default=0)),
                (
                    'user',
                    models.OneToOneField(
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
