# Generated by Django 2.0.10 on 2020-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0072_user_sms_code')]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='flagged_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='flagged_reason',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Streamfarmer'),
                    (1, 'Scam'),
                    (2, 'Samples'),
                    (3, 'Infringements'),
                    (4, 'Infringements claims'),
                    (5, 'DMCA'),
                    (6, 'Payment Fraud'),
                    (7, 'Other'),
                ],
                null=True,
            ),
        ),
    ]
