# Generated by Django 2.0.10 on 2020-06-04 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'users',
            '0073_adding_flagged_reason_and_flagged_at_fields_to_usermetadata_model',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermetadata',
            name='unverified_phone',
        ),
    ]
