# Generated by Django 2.0.13 on 2020-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0074_remove_usermetadata_unverified_phone')]

    operations = [
        migrations.AddField(
            model_name='otpdevice',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Only used for signup'),
        )
    ]
