# Generated by Django 2.0.13 on 2020-07-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0077_rename_related_name')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_signin_id',
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, unique=True
            ),
        )
    ]
