# Generated by Django 2.0.13 on 2020-08-21 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('users', '0078_user_apple_signin_id')]

    operations = [
        migrations.RemoveField(model_name='artistmembership', name='artist'),
        migrations.RemoveField(model_name='artistmembership', name='user'),
        migrations.RemoveField(model_name='artist', name='members'),
        migrations.DeleteModel(name='ArtistMembership'),
    ]
