# Generated by Django 2.0.13 on 2020-08-21 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0103_remove_artist_from_releases'),
        ('users', '0079_remove_artistmembership'),
    ]

    operations = [
        migrations.RemoveField(model_name='artist', name='permissions'),
        migrations.DeleteModel(name='Artist'),
    ]
