# Generated by Django 2.0.13 on 2020-10-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0080_remove_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergdpr',
            name='user_apple_signin_id',
            field=models.BooleanField(default=False),
        ),
    ]
