# Generated by Django 2.0.13 on 2020-10-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0082_usergdpr_user_facebook_id')]

    operations = [
        migrations.AddField(
            model_name='usergdpr',
            name='user_firebase_token',
            field=models.BooleanField(default=False),
        )
    ]
