# Generated by Django 2.0.13 on 2020-10-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0083_usergdpr_user_firebase_token')]

    operations = [
        migrations.AddField(
            model_name='usergdpr',
            name='user_zendesk_id',
            field=models.BooleanField(default=False),
        )
    ]
