# Generated by Django 2.0.13 on 2020-11-11 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0084_usergdpr_user_zendesk_id')]

    operations = [
        migrations.CreateModel(
            name='AppsflyerDevice',
            fields=[
                (
                    'appsflyer_id',
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ('idfa', models.CharField(default=None, max_length=36, null=True)),
                ('idfv', models.CharField(default=None, max_length=36, null=True)),
                ('aaid', models.CharField(default=None, max_length=36, null=True)),
                ('oaid', models.CharField(default=None, max_length=36, null=True)),
                ('imei', models.CharField(default=None, max_length=20, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
