# Generated by Django 2.0.13 on 2020-12-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0085_appsflyerdevice')]

    operations = [
        migrations.AddField(
            model_name='appsflyerdevice',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        )
    ]
