# Generated by Django 2.0.13 on 2020-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0086_appsflyerdevice_updated')]

    operations = [
        migrations.AddField(
            model_name='artistv2',
            name='spotify_for_artists_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalartistv2',
            name='spotify_for_artists_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
