# Generated by Django 2.0.13 on 2021-01-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0087_artistv2_spotify_for_artists_url')]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='impact_click_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        )
    ]
