# Generated by Django 2.1.15 on 2021-03-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0088_usermetadata_impact_click_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='flagged_reason',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Streamfarmer'),
                    (1, 'Scam'),
                    (2, 'Samples'),
                    (3, 'Infringements'),
                    (4, 'Infringements claims'),
                    (5, 'DMCA'),
                    (6, 'Payment Fraud'),
                    (7, 'Other'),
                    (8, 'Restricted country'),
                ],
                null=True,
            ),
        ),
    ]
