# Generated by Django 2.1.15 on 2021-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0090_usermetadata_gdpr_wiped_at')]

    operations = [
        migrations.AddField(
            model_name='artistv2',
            name='audiomack_access_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artistv2',
            name='audiomack_access_token_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='artistv2',
            name='audiomack_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalartistv2',
            name='audiomack_access_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalartistv2',
            name='audiomack_access_token_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalartistv2',
            name='audiomack_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
