# Generated by Django 2.2.25 on 2022-03-29 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('users', '0092_add_delete_requested_flag_meta')]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
