# Generated by Django 2.2.25 on 2022-08-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0093_add_user_comment_related_name')]

    operations = [
        migrations.AddField(
            model_name='usergdpr',
            name='zendesk_data',
            field=models.BooleanField(default=False),
        )
    ]
