# Generated by Django 3.2.15 on 2022-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0094_usergdpr_zendesk_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='licensed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transactionwithdrawal',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userartistrole',
            name='main_artist_profile',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
