# Generated by Django 3.2.15 on 2022-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0095_fix_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergdpr',
            name='segment_data',
            field=models.BooleanField(default=False),
        ),
    ]
