# Generated by Django 3.2.15 on 2022-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0096_usergdpr_segment_data')]

    operations = [
        migrations.AddField(
            model_name='usergdpr',
            name='fuga_data',
            field=models.BooleanField(default=False),
        )
    ]
