# Generated by Django 3.2.15 on 2022-10-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0097_usergdpr_fuga_data')]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='is_fraud_attempted',
            field=models.BooleanField(
                default=False,
                help_text='When active, user is occasionally informed within the web app about payment fraud attempt. No other implications.',
            ),
        )
    ]
