# Generated by Django 3.2.15 on 2022-10-25 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('users', '0098_usermetadata_is_fraud_attempted')]

    operations = [
        migrations.CreateModel(
            name='GDPRRemovalRequest',
            fields=[],
            options={
                'verbose_name': 'GDPR Removal Request',
                'verbose_name_plural': 'GDPR Removal Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        )
    ]
