# Generated by Django 3.2.15 on 2023-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0101_add_autogenerated_artistv2')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fuga_migration',
            field=models.BooleanField(default=False),
        )
    ]
