# Generated by Django 2.1.15 on 2021-08-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payouts', '0001_payout_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='revenue_system_id',
            field=models.CharField(
                blank=True,
                help_text='Revenue system payment identifier',
                max_length=255,
                null=True,
            ),
        ),
    ]
