# Generated by Django 2.1.15 on 2021-08-24 09:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0007_exchange_rate'),
        ('payouts', '0002_payment_revenue_system_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMethodConfiguration',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.CharField(max_length=125)),
                (
                    'fee',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    'limits',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        default=5,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='countries.Currency',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='payouts.Provider',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='transfermethod',
            name='currency',
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.PROTECT,
                to='countries.Currency',
            ),
        ),
    ]
