# Generated by Django 2.1.15 on 2021-08-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0007_exchange_rate'),
        ('payouts', '0003_trm_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermethodconfiguration',
            name='country',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='countries.Country',
            ),
        ),
    ]
