# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-06 10:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0040_contributor_apple_id'),
        ('amuse', '0001_utils_notification-template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcoding',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'transcoder_job',
                    models.CharField(max_length=120, null=True, unique=True),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'SUBMITTED'),
                            (1, 'COMPLETED'),
                            (2, 'PROGRESSING'),
                            (3, 'WARNING'),
                            (4, 'ERROR'),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    'errors',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        default=[],
                        size=None,
                    ),
                ),
                (
                    'warnings',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        default=[],
                        size=None,
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='releases.Song'
                    ),
                ),
            ],
            options={'db_table': 'transcoding'},
        )
    ]
