# Generated by Django 2.0.7 on 2018-08-04 14:15

import amuse.models.deliveries
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0058_inactivate_groove_music'),
        ('amuse', '0002_transcoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDelivery',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'delivery_id',
                    models.CharField(
                        default=amuse.models.deliveries._batch_delivery_id,
                        max_length=18,
                    ),
                ),
                (
                    'channel',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'fuga'), (2, 'apple'), (3, 'spotify')]
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'created'),
                            (1, 'succeeded'),
                            (50, 'ambiguous'),
                            (99, 'failed'),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'batch_delivery'},
        ),
        migrations.CreateModel(
            name='BatchDeliveryRelease',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'created'),
                            (1, 'started'),
                            (2, 'succeeded'),
                            (99, 'failed'),
                        ],
                        default=0,
                    ),
                ),
                (
                    'errors',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        default=[],
                        size=None,
                    ),
                ),
                (
                    'warnings',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        default=[],
                        size=None,
                    ),
                ),
                (
                    'delivery',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='amuse.BatchDelivery',
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Release',
                    ),
                ),
            ],
            options={'db_table': 'batch_delivery_release'},
        ),
        migrations.AddField(
            model_name='batchdelivery',
            name='releases',
            field=models.ManyToManyField(
                through='amuse.BatchDeliveryRelease', to='releases.Release'
            ),
        ),
    ]
