# Generated by Django 2.0.8 on 2018-08-23 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0003_batch_deliveries')]

    operations = [
        migrations.AlterField(
            model_name='batchdeliveryrelease',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name='batchdeliveryrelease',
            name='warnings',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512), default=list, size=None
            ),
        ),
    ]
