# Generated by Django 2.0.8 on 2018-11-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0004_batch_delivery_defaults')]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField()),
                ('mime', models.TextField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
            ],
        )
    ]
