# Generated by Django 2.0.8 on 2018-11-22 11:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0073_store_logo_color'),
        ('amuse', '0006_batchdeliverytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACRCloudMatch',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('score', models.PositiveSmallIntegerField()),
                ('offset', models.PositiveSmallIntegerField()),
                ('artist_name', models.CharField(max_length=255)),
                ('album_title', models.CharField(max_length=255)),
                ('track_title', models.CharField(max_length=255)),
                ('match_upc', models.CharField(max_length=13, null=True)),
                ('match_isrc', models.CharField(max_length=12, null=True)),
                (
                    'external_metadata',
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='acrcloud_matches',
                        to='releases.Song',
                    ),
                ),
            ],
            options={'db_table': 'acrcloud_match'},
        )
    ]
