# Generated by Django 2.0.8 on 2018-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0008_acrcloud_fields')]

    operations = [
        migrations.AlterField(
            model_name='batchdelivery',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'created'),
                    (1, 'succeeded'),
                    (10, 'started'),
                    (50, 'ambiguous'),
                    (99, 'failed'),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='batchdeliveryrelease',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'created'),
                    (1, 'started'),
                    (2, 'succeeded'),
                    (10, 'storing'),
                    (99, 'failed'),
                ],
                default=0,
            ),
        ),
    ]
