# Generated by Django 2.0.8 on 2018-12-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('countries', '0002_country_region_code'),
        ('amuse', '0009_batchdeliverystatuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.PositiveIntegerField(
                        choices=[(1, 'create'), (2, 'update'), (3, 'login')]
                    ),
                ),
                (
                    'client',
                    models.PositiveIntegerField(
                        choices=[(1, 'android'), (2, 'ios'), (3, 'web'), (4, 'other')]
                    ),
                ),
                ('version', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.ContentType',
                    ),
                ),
                (
                    'country',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='countries.Country',
                    ),
                ),
            ],
        )
    ]
