# Generated by Django 2.0.8 on 2019-01-07 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('releases', '0073_store_logo_color'),
        ('amuse', '0010_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'event',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'assigned'),
                            (2, 'prepared'),
                            (3, 'approved'),
                            (4, 'rejected'),
                        ]
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Release',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SupportRelease',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('prepared', models.BooleanField(default=False)),
                ('date_cated', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                (
                    'assignee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'release',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Release',
                    ),
                ),
            ],
        ),
    ]
