# Generated by Django 2.0.10 on 2019-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0073_store_logo_color'),
        ('amuse', '0012_batchdeliveryrelase_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdeliveryrelease',
            name='excluded_stores',
            field=models.ManyToManyField(
                blank=True,
                help_text='This is the stores to <strong>exclude</strong> from delivery.',
                to='releases.Store',
            ),
        )
    ]
