# Generated by Django 2.0.10 on 2019-09-04 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('amuse', '0015_minfraud_parse_response_body')]

    operations = [
        migrations.AlterField(
            model_name='minfraudresult',
            name='release',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='releases.Release',
            ),
        ),
        migrations.AlterField(
            model_name='minfraudresult',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
