# Generated by Django 2.0.10 on 2020-01-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0017_minfraud_risk_to_fraud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdelivery',
            name='channel',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'fuga'), (2, 'apple'), (3, 'spotify'), (4, 'tiktok')]
            ),
        ),
    ]
