# Generated by Django 2.0.10 on 2020-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0020_transcoding_transcoder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdelivery',
            name='channel',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'fuga'),
                    (2, 'apple'),
                    (3, 'spotify'),
                    (4, 'tiktok'),
                    (5, 'soundcloud'),
                    (6, 'sevendigital'),
                ]
            ),
        ),
    ]
