# Generated by Django 2.0.13 on 2020-11-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0022_auto_20200608_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdelivery',
            name='channel',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'fuga'),
                    (2, 'apple'),
                    (3, 'spotify'),
                    (4, 'tiktok'),
                    (5, 'soundcloud'),
                    (6, 'sevendigital'),
                    (7, 'amazon'),
                ]
            ),
        ),
    ]
