# Generated by Django 2.1.15 on 2021-02-23 10:24

import amuse.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0024_fix-postgres-error-E003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        storage=amuse.storages.S3Storage(
                            bucket_name=settings.AWS_BATCH_DELIVERY_FILE_BUCKET_NAME
                        ),
                        upload_to='',
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'created'),
                            (1, 'succeeded'),
                            (98, 'started'),
                            (99, 'failed'),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='batchdelivery',
            name='batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='amuse.Batch',
            ),
        ),
    ]
