# Generated by Django 2.0.13 on 2021-02-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0025_batch_class')]

    operations = [
        migrations.AlterField(
            model_name='batchdelivery',
            name='channel',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'fuga'),
                    (2, 'apple'),
                    (3, 'spotify'),
                    (4, 'tiktok'),
                    (5, 'soundcloud'),
                    (6, 'sevendigital'),
                    (7, 'amazon'),
                    (8, 'anghami'),
                    (9, 'claro_musica'),
                    (10, 'deezer'),
                    (11, 'nuuday'),
                    (12, 'tidal'),
                    (13, 'youtube_content_id'),
                    (14, 'youtube_music'),
                    (15, 'facebook'),
                ]
            ),
        )
    ]
