# Generated by Django 2.1.15 on 2021-03-09 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('amuse', '0026_add_channels')]

    operations = [
        migrations.AlterModelOptions(
            name='batch', options={'verbose_name_plural': 'Batches'}
        ),
        migrations.AlterModelOptions(
            name='batchdelivery', options={'verbose_name_plural': 'Batch Deliveries'}
        ),
    ]
