# Generated by Django 2.0.13 on 2021-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0108_store_parent'),
        ('amuse', '0027_deliveries_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdeliveryrelease',
            name='stores',
            field=models.ManyToManyField(
                blank=True,
                help_text='This is a static snapshot of the stores delivered to.',
                related_name='delivery_stores',
                to='releases.Store',
            ),
        ),
    ]
