# Generated by Django 2.1.15 on 2021-04-23 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0029_add_redeliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdeliveryrelease',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2048), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name='batchdeliveryrelease',
            name='warnings',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2048), default=list, size=None
            ),
        ),
    ]
