# Generated by Django 2.1.15 on 2021-04-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0030_increase_error_warning_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdeliveryrelease',
            name='redeliveries',
            field=models.ManyToManyField(
                blank=True,
                help_text='Redeliveries of this delivery',
                to='amuse.BatchDeliveryRelease',
            ),
        ),
    ]
