# Generated by Django 2.1.15 on 2021-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0033_add_shazam_channel')]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=120, unique=True)),
                ('link', models.URLField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
