# Generated by Django 2.1.15 on 2021-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0036_add_boomplay_channel')]

    operations = [
        migrations.AlterField(
            model_name='batchdelivery',
            name='channel',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'fuga'),
                    (2, 'apple'),
                    (3, 'spotify'),
                    (4, 'tiktok'),
                    (5, 'soundcloud'),
                    (6, 'sevendigital'),
                    (7, 'amazon'),
                    (8, 'anghami'),
                    (9, 'claro_musica'),
                    (10, 'deezer'),
                    (11, 'nuuday'),
                    (12, 'tidal'),
                    (13, 'youtube_content_id'),
                    (14, 'youtube_music'),
                    (15, 'facebook'),
                    (16, 'twitch'),
                    (17, 'shazam'),
                    (18, 'audiomack'),
                    (19, 'boomplay'),
                    (20, 'pandora'),
                ]
            ),
        )
    ]
