# Generated by Django 2.1.15 on 2021-12-13 07:58

from django.conf import settings
from django.db import migrations, models

import amuse.storages


class Migration(migrations.Migration):
    dependencies = [('amuse', '0042_add_iheart_channel')]

    operations = [
        migrations.AlterField(
            model_name='bulkdeliveryjob',
            name='output_file',
            field=models.FileField(
                editable=False,
                help_text='Results of the bulk delivery job will be available here after processing',
                storage=amuse.storages.S3Storage(
                    bucket_name=settings.AWS_BULK_DELIVERY_JOB_BUCKET_NAME
                ),
                upload_to='output/',
            ),
        )
    ]
