# Generated by Django 2.2.25 on 2022-02-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('amuse', '0044_bulkdeliveryjobresult')]

    operations = [
        migrations.RemoveField(model_name='bulkdeliveryjob', name='output_file'),
        migrations.RemoveField(model_name='bulkdeliveryjobresult', name='delivery'),
        migrations.AddField(
            model_name='bulkdeliveryjob',
            name='mode',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Add release stores'),
                    (1, 'Override release stores'),
                    (2, 'Only release stores'),
                    (3, 'Only fuga release stores'),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AddField(
            model_name='bulkdeliveryjobresult',
            name='batch',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='amuse.Batch',
            ),
        ),
        migrations.AlterField(
            model_name='bulkdeliveryjob',
            name='stores',
            field=models.ManyToManyField(
                blank=True,
                help_text='Stores to perform the bulk operation towards.',
                to='releases.Store',
            ),
        ),
        migrations.AlterField(
            model_name='bulkdeliveryjob',
            name='type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'insert'),
                    (3, 'full update'),
                    (1, 'update metadata'),
                    (2, 'takedown'),
                ],
                db_index=True,
                default=0,
                help_text='Type of bulk operation to perform',
            ),
        ),
    ]
