# Generated by Django 2.2.25 on 2022-02-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0116_store_extra_info'),
        ('amuse', '0047_bulkdeliveryjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdeliveryjobresult',
            name='store',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='releases.Store',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='bulkdeliveryjobresult', unique_together={('job', 'release', 'store')}
        ),
    ]
