# Generated by Django 2.2.25 on 2022-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0048_bulkdeliveryjobresult_store')]

    operations = [
        migrations.AddField(
            model_name='bulkdeliveryjob',
            name='execute_at',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
