# Generated by Django 2.2.25 on 2022-05-06 09:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0049_bulkdeliveryjob_execute_at')]

    operations = [
        migrations.AddField(
            model_name='bulkdeliveryjob',
            name='checks_to_override',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=256),
                default=list,
                size=None,
            ),
        )
    ]
