# Generated by Django 2.2.25 on 2022-07-11 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('releases', '0120_add_hexcolor_field'),
        ('amuse', '0052_add_resso_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseTakedownRequest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'takedown_reason',
                    models.CharField(
                        choices=[
                            ('switch_distributor', 'Switch distributor'),
                            ('dislike_release', 'Dislike release'),
                            ('change_audio', 'Changing audio'),
                            ('change_isrc', 'Changing ISRC'),
                            ('signed_to_label', 'Signed to label'),
                            ('other', 'Other'),
                        ],
                        max_length=32,
                    ),
                ),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                (
                    'release',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='releases.Release',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
