# Generated by Django 3.2.15 on 2022-10-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('amuse', '0056_fix_warnings')]

    operations = [
        migrations.AddField(
            model_name='bulkdeliveryjob',
            name='ignore_release_status',
            field=models.BooleanField(default=False),
        )
    ]
