# Generated by Django 3.2.15 on 2023-02-07 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('amuse', '0059_alter_bulkdeliveryjob_store')]

    operations = [migrations.RemoveField(model_name='bulkdeliveryjob', name='stores')]
