# Generated by Django 3.2.15 on 2023-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amuse', '0060_remove_bulkdeliveryjob_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdeliveryjob',
            name='youtube_content_id',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
