# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-04 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [('releases', '0034_merge')]

    operations = [
        migrations.CreateModel(
            name='ApprovedRelease',
            fields=[],
            options={'proxy': True},
            bases=('releases.release',),
        ),
        migrations.CreateModel(
            name='GenericRelease',
            fields=[],
            options={'proxy': True},
            bases=('releases.release',),
        ),
        migrations.CreateModel(
            name='NotApprovedRelease',
            fields=[],
            options={'proxy': True},
            bases=('releases.release',),
        ),
        migrations.CreateModel(
            name='PendingRelease',
            fields=[],
            options={'proxy': True},
            bases=('releases.release',),
        ),
        migrations.CreateModel(
            name='RejectedRelease',
            fields=[],
            options={'proxy': True},
            bases=('releases.release',),
        ),
    ]
