# Generated by Django 2.0.8 on 2019-01-07 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0073_store_logo_color'),
        ('contenttollgate', '0002_deliveredrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPendingRelease',
            fields=[],
            options={'proxy': True, 'indexes': []},
            bases=('releases.release',),
        ),
        migrations.CreateModel(
            name='AssignedPreparedRelease',
            fields=[],
            options={'proxy': True, 'indexes': []},
            bases=('releases.release',),
        ),
    ]
