# Generated by Django 2.0.13 on 2020-10-02 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0103_remove_artist_from_releases'),
        ('contenttollgate', '0004_urgentprorelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentFreeRelease',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('releases.release',),
        ),
    ]
