# Generated by Django 2.0.13 on 2020-10-02 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0103_remove_artist_from_releases'),
        ('contenttollgate', '0005_urgentfreerelease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrgentFreeRelease',
        ),
        migrations.DeleteModel(
            name='UrgentProRelease',
        ),
        migrations.CreateModel(
            name='FreeRelease',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('releases.release',),
        ),
        migrations.CreateModel(
            name='ProRelease',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('releases.release',),
        ),
    ]
