# Generated by Django 2.0.13 on 2021-01-29 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('releases', '0104_add_is_lyrics_and_is_title_to_languages'),
        ('contenttollgate', '0006_rename_urgentrelease_to_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusRelease',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('releases.release',),
        ),
    ]
